### ISSUE TITLE
Update binaries description in the releases

### ISSUE THREAD

**Issue by rvem** [serokell/tezos-packaging#102]
# Clarification and motivation
We include some short descriptions of the binaries in the releases. These descriptions should be revised.
1) Revise all descriptions for sanity. Specifically for `tezos-codec` when #85 is resolved.
2) It makes sense to include protocol name for all daemons, for example:
    * `tezos-baker-007-PsDELPH1`: Baking daemon for Delphi protocol.
3) Provide links to the upstream documentation on GitLab. E.g. http://tezos.gitlab.io/api/cli-commands.html#client-manual

# Acceptance criteria
Releases description is updated in accordance with the listed points.

**Comment by pasqu4le** [comment]
I think that for this issue the last point would actually cover all needs for descriptions.

We do this on the README already:
> See the [official documentation](http://tezos.gitlab.io/introduction/howtouse.html) for information about the binaries, their usage, and concepts about the Tezos networks

and since that link points to up-to-date descriptions now I think it makes senses to do the same here.
