### ISSUE TITLE
Build binaries for macOS 

### ISSUE THREAD

**Issue by rvem** [serokell/tezos-packaging#103]
# Clarification and motivation
There is a rumor that now we have a mac builder. We should use it in order to build Tezos binaries for macOS.

In addition, we can have brew formulas for them.

# Acceptance criteria
CI builds binaries that target macOS, these binaries are included in the releases.

We provide brew formulas for Tezos binaries

**Comment by gromakovsky** [comment]
Some `brew` stuff developed/maintained by TQ: https://github.com/tqtezos/homebrew-tq. We can use something from there. If we properly incorporate packaging for MacOS into this repo, probably `homebrew-tq` can be deprecated/archived.

**Comment by gromakovsky** [comment]
> CI builds binaries that target macOS, these binaries are included in the releases.

> We provide brew formulas for Tezos binaries

We can do only one of these two: either `brew` formulas or portable executables. AFAIU you can't make a fully static binary because you can't link statically with libc, but in case of MacOS linking dynamically should be ok because there is only one libc.

**Comment by gromakovsky** [comment]
Also in case of `brew` it'd be nice to provide pre-compiled stuff, so that users wouldn't have to build anything on their machine. IIRC when I `brew install tezos` on my old MacBook it compiles a lot of stuff.

**Comment by rvem** [comment]
I think we can make `brew` download macOS binaries from the latest release instead of building it from scratch
