### ISSUE TITLE
Add nixos modules for tezos binaries

### ISSUE THREAD

**Issue by rvem** [serokell/tezos-packaging#107]
# Clarification and motivation

We're already using tezos-node nixos module for our infrastructure. However, it's currently located in a private repo,
it would be nice to share it.

Also, we're providing systemd services for `tezos-node` and daemons (accuser, baker, endorser) in the native packages. It'd be nice to have nixos modules for them as well.

# Acceptance criteria
This repo provides an easy way to run nixos modules with `tezos-node`, `tezos-{accuser, baker, endorser}-<proto>` and `tezos-signer`.

**Comment by mkaito** [comment]
Something something flakes
