### ISSUE TITLE
Build tezos-sandbox

### ISSUE THREAD

**Issue by itkach** [serokell/tezos-packaging#109]
# Clarification and motivation

tezos-sandbox is a program for setting up and running test scenarios with the blockchain. This is optional part of Tezos suite that is not built by default. It is useful for developers working on Tezos applications that monitor and index the chain.

# Acceptance criteria

tezos-sandbox binary is built and packaged the same way as the rest of tezos binaries

**Comment by rvem** [comment]
Looks like `tezos-sandbox` binary should be used along with `tezos-{daemon}-alpha` by default.
Does it make sense to bundle `tezos-sandbox` along with these `alpha` daemons and `tezos-client` instead of providing
single `tezos-sandbox` binary?
