### ISSUE TITLE
Make it easier to get static binary

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-packaging#11]
# Clarification and motivation

Currently if one wants to get `tezos-client` static binary they should
> Go to the latest master build, click on build and package stage, choose Artifacts section and download files by clcking on the filenames.

It's not too many steps, but still a bit inconvenient if the only reason why I opened this repo is to get static binary.

# Acceptance criteria

A bit subjective: make it easier to obtain static `tezos-client` binary. We don't really care about `.deb` because people can use `add-apt-repository` and it's written in README. I am not sure about `.rpm`. Anyway, if it's easy to do the same for `.deb` and `.rpm`, let's do it.

Possible options:
1. Use GitHub releases, somehow ensure that up-to-date binaries are there (either create a new release automatically or at least add a checkmark to PR template).
2. Upload artifacts somewhere, get a link pointing to the latest "somewhere", put it into README.

**Comment by itkach** [comment]
I think automatically uploading to GitHub Releases would be nice. I like how [Stack (for example) does it](https://github.com/commercialhaskell/stack/releases/tag/v2.1.3), although it's directly applicable here since this project is packaging another project which itself doesn't seem to have any notion of "release".

**Comment by balsoft** [comment]
This should already be fixed?

**Comment by balsoft** [comment]
Ah, sorry, wrong repo. Is my help needed?

**Comment by itkach** [comment]
We would like to have direct download link to tezos-client static binary so that we can use it in tutorials like https://assets.tqtezos.com/quickstart/1-index

**Comment by gromakovsky** [comment]
Latest release is available at https://github.com/serokell/tezos-packaging/releases/latest

**Comment by gromakovsky** [comment]
`tezos-client`:
* for mainnet: https://github.com/serokell/tezos-packaging/releases/download/202001141534/tezos-client-mainnet-94f779a7
* for babylonnet: https://github.com/serokell/tezos-packaging/releases/download/202001141534/tezos-client-babylonnet-b8731913

These links point to a particular version. If links to "latest" version are needed, we need to do something smarter. Alternatively, one can use `hub` utility to download assets.

**Comment by gromakovsky** [comment]
Ah, it turned out to be possible to download assets from latest release https://help.github.com/en/github/administering-a-repository/linking-to-releases#linking-to-the-latest-release

So all we have to do is make sure that each release contains not only `tezos-client-mainnet-REVISION` but also `tezos-client-mainnet`. I don't know whether one can put symlinks into releases, but in the worst case putting a copy should be fine as well.
In this case link to the latest release will be
> https://github.com/serokell/tezos-packaging/releases/latest/download/tezos-client-mainnet
while currently it is
> https://github.com/serokell/tezos-packaging/releases/latest/download/tezos-client-mainnet-94f779a7

The same should be done for `tezos-client-babylonnet` at least.

@rvem please do it.

**Comment by rvem** [comment]
These changes will be performed as a part of #18.

**Comment by gromakovsky** [comment]
#18 was merged, now https://github.com/serokell/tezos-packaging/releases/latest/download/tezos-client-mainnet works and can be used to download latest released `tezos-client` for mainnet (similar link will work for babylonnet).
