### ISSUE TITLE
Sign artifacts and provide hash sums

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-packaging#114]
# Clarification and motivation

People want to be more confident that artifacts they use can be trusted. E. g. if I obtain our static `tezos-client` somehow, I want to be sure it was provided by Serokell and is genuine as long as I trust Serokell (or, if we move packaging to `tezos/tezos`, trust Tezos developers).

There are at least two natural ways to do that:
1. Sign each artifact using our key (e. g. we can generate a fresh key specifically for this repo), provide our public key somewhere, provide signatures along with artifacts.
2. Provide hash sum (e. g. sha256) for each artifact.

As an example, I see that `stack` releases include `.asc` and `.sha256` files for each artifact: https://github.com/commercialhaskell/stack/releases/tag/v2.5.1

For `.deb` and `.rpm` packages it might be (and actually is quite likely) possible to include signatures into packages themselves. We should explore this opportunity.

# Acceptance criteria

1. We provide at least one way to (quickly and easily) verify our artifacts.
2. For packages we use some standard approach if it exists.

**Comment by rvem** [comment]
Btw, ubuntu packages are already signed by my gpg key
