### ISSUE TITLE
Find a way to test protocol updates

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-packaging#115]
# Clarification and motivation

Sometimes a protocol upgrade takes place in Tezos. It's a rare special case that we should pay attention to.When a protocol update happens, usually you have to run 2 bakers (for the old protocol and the new one). We would like to be sure that our binaries work correctly in such scenario. So we need a way to test this scenario.

There is the following test that apparently does something relevant and might be useful: https://gitlab.com/tezos-kiln/kiln/-/blob/f9061ce490484fe16f02391e8d745851751ae130/tests/default.nix

# Acceptance criteria

1. We can quickly test protocol update scenario. Run a test network, update protocol there while running 2 bakers (and maybe other daemons), check that all daemons behave as expected.
2. Ideally it should be automated and be part of CI, but if there are reasons not to do that, let's at least be able to test manually.

**Comment by rvem** [comment]
Now we have a [script](https://gitlab.com/morley-framework/local-chain#voting-scenario) that goes through the Tezos voting cycle. It can be used to test protocol upgrades. Additionally, we have a [dedicated doc](https://github.com/serokell/tezos-packaging/blob/master/docs/tests/voting.md) that explains how to test protocol upgrade and voting via the wizard.
So I believe we can consider this issue resolved now.
