### ISSUE TITLE
version 7.5 is still not in ppa

### ISSUE THREAD

**Issue by chiptus** [serokell/tezos-packaging#123]
Running `sudo apt update && sudo apt upgrade` doesn't upgrade tezos-client. The version that is in the ppa is still 7.4:0

**Comment by rvem** [comment]
Unfortunately, our ubuntu packaging is based on the tezos opam packages:(
So we blocked by the https://gitlab.com/tezos/tezos/-/issues/1021

**Comment by rvem** [comment]
@chiptus, sorry for such a long response. v8.1 was published to the launchpad, should become available soon (there are still some builds running, everything should be available within 20-25 minutes, I think)

**Comment by chiptus** [comment]
thanks! and thanks for letting me know!

>

**Comment by rvem** [comment]
Let me know if this issue can be closed now

**Comment by chiptus** [comment]
IMO yes, closing
