### ISSUE TITLE
[BUG] Unable to import snapshot with version 8.1-1

### ISSUE THREAD

**Issue by emmanueldenloye** [serokell/tezos-packaging#128]
# Description

While using Kiln Classic (https://gitlab.com/tezos-kiln/kiln), I attempted to import a snapshot. In my build of Kiln, I am using the binaries produced from your latest release. Initially, tezos-node couldn't find the sapling parameter files it needed. Once I was able to put to a valid location for these files, I received an error message from Rust.

# To Reproduce

Attempt to start a tezos-node from a snapshot like this

```
% export RUST_BACKTRACE=1
eod at eod in ~
% /nix/store/5dybr0qbjm771pmf1kfnf7aa5lvh393m-tezos-8.1-1/bin/tezos-node run --snapshot ~/Downloads/delphinet-2021-01-14_14-01.rolling
```

# Expected behavior

A working tezos-node. However this is error I get

```
thread '<unnamed>' panicked at 'couldn't load Sapling spend parameters file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/zcash_proofs-0.2.0/src/lib.rs:38:20
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

# Environment

OS - Arch Linux
tag - v8.1-1

**Comment by rvem** [comment]
I'm looking at the `tezos-node run --help` and don't anything about the `--snapshot` option, looks like I'm missing something :thinking: 

Also, could you please provide the snapshot file that you've tried to use?

I've tried to import rolling snapshot locally via
```
$ tezos-node snapshot import --data-dir test snapshot-testnet_20-01-2021-0149_376581_BLBqk7HPxtck1LJxfBboTjpTqZpn1goFZATvQhR2WxAqHYLJyrJ.rolling --block BLBqk7HPxtck1LJxfBboTjpTqZpn1goFZATvQhR2WxAqHYLJyrJ
```
Using [this snapshot](https://snapshots-tezos.giganode.io/snapshot-testnet_20-01-2021-0149_376581_BLBqk7HPxtck1LJxfBboTjpTqZpn1goFZATvQhR2WxAqHYLJyrJ.rolling) and the import went well, as well
as the node start.

**Comment by emmanueldenloye** [comment]
I've resolved the issue. There is no bug. I'll close this issue.
