### ISSUE TITLE
Build/package other tezos binaries 

### ISSUE THREAD

**Issue by itkach** [serokell/tezos-packaging#14]
# Clarification and motivation

In addition to `tezos-client`, Tezos software also includes other binaries: `tezos-admin-client`, `tezos-node`, `tezos-baker`, `tezos-accuser`, `tezos-endorser`, `tezos-signer` and `tezos-protocol-compiler`. Same as with `tezos-client`, availability of easy-to-install native platform binaries would lower barrier for adoption and make it easier for developers to start experimenting and building tools and applications for Tezos platform.

# Acceptance criteria
Statically linked binaries and/or packages for popular Linux distros are available for download.

**Comment by gromakovsky** [comment]
We should also rename the repo once again, probably to `tezos-packaging`.
