### ISSUE TITLE
Consider adding aliases for commands on Ubuntu

### ISSUE THREAD

**Issue by pasqu4le** [serokell/tezos-packaging#148]
# Clarification and motivation

As part of the explanation for #125 it is apparent that there is the need to call several `tezos-*` commands wuth the `tezos` user in order to set up baking.

However in the case of `tezos-node`, many of these calls require the user to specify the `data-dir` to be used.

To improve UX I propose to add `tezos-node-<network>` during installation (to be used by the `tezos` user), which are just aliases to `tezos-node` with the correct data directory set.
These should make its use more straightforward as their name would match the one of the corresponding `systemd` services.
 
# Acceptance criteria

There should be aliases available to the `tezos` user to call `tezos-node` without having to specify the `--data-dir`.

**Comment by rvem** [comment]
Seems to be blocked by the https://gitlab.com/tezos/tezos/-/issues/1118

**Comment by rvem** [comment]
Additionally, we should add `--network <network>` option to the aliases scripts along with `TEZOS_NODE_DIR` env variable

**Comment by pasqu4le** [comment]
See [this comment](https://github.com/serokell/tezos-packaging/pull/164#discussion_r621288189): I propose setting different RPC ports for different networks and as a consequence I suggest extending the scope of this issue to also add `tezos-clinet-<network>` aliases.
