### ISSUE TITLE
Static binaries for the next protocol release candidates

### ISSUE THREAD

**Issue by m-kus** [serokell/tezos-packaging#151]
We have a task to set up a continuous integration testing pipeline for our products against new protocol versions. The main reason is to be able to spot issues (both in our codebase and the core) as early as possible, and thus give feedback before the protocol injection.  

Currently there are nightly [docker builds](https://gitlab.com/nomadic-labs/tezos/container_registry/1572522) provided by NL, but they are very large and generally an overkill for our task, because we only need the tezos-node binary (and sapling params).  

On the other hand, static binaries provided in your releases work like a charm, and our sandbox images (built on top) are only 90M. The only thing we miss is a rolling "next" pre-release containing code from the RC branch (e.g. now it's *falphanet-release*).

# Acceptance criteria

An additional rolling pre-release (or separate pre-releases for each new protocol) containing static binaries. The trigger rule is a subject for discussion.

**Comment by rvem** [comment]
https://github.com/serokell/tezos-packaging/releases/tag/falphanet-release
