### ISSUE TITLE
Provide network specific systemd pseudo-services for baking

### ISSUE THREAD

**Issue by itkach** [serokell/tezos-packaging#156]
# Clarification and motivation

Tezos users may want to set up baking on a particular network, such as mainnet or a test network for current or upcoming protocol. This involves configuring and starting a set of daemons - baker, endorser and, optionally, accuser,  - for the network's current protocol, and possibly, in case of protocol upgradeable network such as mainnet,  the same set of daemons for the upcoming protocol. Providing individual baker, endorser and accuser services per protocol allows to achieve this, but is not convenient. Also, there are some configuration and inter-service hard and soft dependencies that are not codified: baker service needs to be configured to point to node's data directory, baker and endorser services should be running (or not running) at the same time, node service should be running when baker and endorser are running etc.

A systemd service can be provided to control these several cooperating daemons together, along the lines of what is described in https://alesnosek.com/blog/2016/12/04/controlling-a-multi-service-application-with-systemd/. Modifying this service definition and rolling out these modifications as a regular package update will allow to automatically prepare running bakers for an upcoming protocol upgrade.

# Acceptance criteria

User can start baking on a known network with a single command like so:

```
$ sudo systemctl start tezos-baking-mainnet
```

provided user's private key has been imported and designated for baking.

If system is missing pre-requisits, the command may fail and provide further user instructions, or perhaps even launch configuration script that would guide user through private key import and baker registration, wrapping corresponding tezos-client comands and modifying config files as necessary.

**Comment by pasqu4le** [comment]
Fixed in v9.1-1 native packages
