### ISSUE TITLE
SHA256 mismatch installing via brew

### ISSUE THREAD

**Issue by kevinkilroy** [serokell/tezos-packaging#166]
Cannot install on MacOS via brew:

`brew install tezos-client
==> Installing tezos-client from serokell/tezos-packaging
==> Downloading https://github.com/serokell/tezos-packaging/releases/download/v8
==> Downloading from https://github-releases.githubusercontent.com/219989982/814
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 2921c9a5bec843fbd3806660ae4911d43ff2fac7adc2ccaee674e7bfc27d3771
  Actual: 5f7a5687d67051eafcfb7cb5ac542143a325a135403daeca6595602bfd400441`

Tried several times, same issue each time

**Comment by pasqu4le** [comment]
Hi @kevinkilroy , thanks for reporting this.

The bottle hashes for `tezos-sapling-params` were mistakenly updated recently, the problem should now be fixed.
