### ISSUE TITLE
Installation problems for binary package tezos-baker-009-psfloren

### ISSUE THREAD

**Issue by NicVolanschi** [serokell/tezos-packaging#198]
# Description

When trying to install the new Florence-based binary packages, we get a post-installation error on tezos-baker-009-psfloren.

# To Reproduce

    docker run --rm -it public.ecr.aws/lts/ubuntu:18.04_stable
    apt-get update
    apt-get install sudo
    apt-get install -y software-properties-common </dev/null
    sudo add-apt-repository ppa:serokell/tezos && sudo apt-get update
    sudo apt-get install -y tezos-client
    sudo apt-get install -y tezos-node
    sudo apt-get install -y tezos-baker-009-psfloren

Produces this error:

    Unpacking tezos-baker-009-psfloren (2:9.1-0ubuntu2~bionic) ...
    Setting up acl (2.2.52-3build1) ...
    Setting up tezos-baker-009-psfloren (2:9.1-0ubuntu2~bionic) ...
    useradd: user 'tezos' already exists
    /var/lib/dpkg/info/tezos-baker-009-psfloren.postinst: 72: /var/lib/dpkg/info/tezos-baker-009-psfloren.postinst:     cannot create /etc/udev/rules.d/20-hw1.rules: Directory nonexistent
    dpkg: error processing package tezos-baker-009-psfloren (--configure):
     installed tezos-baker-009-psfloren package post-installation script subprocess returned error exit status 2

# Expected behavior

# Environment

- OS: docker run --rm -it public.ecr.aws/lts/ubuntu:18.04_stable
- branch/revision

# Additional context

**Comment by rvem** [comment]
Fixed in 9.1-3 native packages
