### ISSUE TITLE
Create the first version of a packaging wizard

### ISSUE THREAD

**Issue by pasqu4le** [serokell/tezos-packaging#201]
# Clarification and motivation

We want to have an interactive way for people to set up baking (or just a node) that doesn't involve inputting many commands in the terminal.

To do so an option is to add a new native package that contains a CLI wizard utility.

For a first version this wizard should be able to guide the user through the steps that are currently described in the [baking article](https://github.com/serokell/tezos-packaging/blob/master/docs/baking.md), provide choices interactively for the options available and execute the commands (mainly `systemctl`) for them.

# Acceptance criteria

A new native package (`tezos-baking-setup` ?) provides a wizard for easier set-up of tezos configuration and `systemd` services.
It should be able to;
- interactively ask for:
   -  the network to use
   - if the user wants to run only a node or also baking
   - what type of baker key import to use
- provide suggestions for the options above as well
- wait for the step that require some time
- manage (at least launch) `systemd` services
- set up what necessary for the `tezos` user

**Comment by rvem** [comment]
something about snapshot import?

**Comment by rvem** [comment]
> A new native package (tezos-baking-setup ?) provides a wizard for easier set-up of tezos configuration and systemd services.

I think that wizard can be installed along with `tezos-baking` package. Currently, this package provides only systemd services
