### ISSUE TITLE
[BUG] Fail to install tezos-client on Ubuntu subsytem for Windows

### ISSUE THREAD

**Issue by GuillaumeGen** [serokell/tezos-packaging#202]
# Description

When I try to install tezos-client, it fails with the following error message:

```
Setting up tezos-client (2:9.1-0ubuntu3~focal) ...
Failed to send reload request: No such file or directory
dpkg: error processing package tezos-client (--configure):
 installed tezos-client package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 tezos-client
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

# To Reproduce

I ran `sudo add-apt-repository ppa:serokell/tezos && sudo apt-get update` which worked fine and then `sudo apt install tezos-client`

# Expected behavior

The package to be installed and no error message to be printed.

# Environment

- Windows 10 Version 20H2 (build 19042.985)
- WSL: Ubuntu 20.04.2 LTS

**Comment by rvem** [comment]
Fixed in `2:9.1-0ubuntu4` `tezos-client`
