### ISSUE TITLE
PPA for Ubuntu 21.04 "Hirsute"

### ISSUE THREAD

**Issue by jordan-tezos** [serokell/tezos-packaging#212]
Ubuntu Hirsute has been released on 2121-04-22 but the `tezos-*` executables are not available yet on it.

> The http://ppa.launchpad.net/serokell/tezos/ubuntu hirsute Release repository does not have a Release file.

**Comment by rvem** [comment]
We've published `9.1-0ubuntu4` packages for 21.04
