### ISSUE TITLE
[BUG] tezos node service is not restarted on update

### ISSUE THREAD

**Issue by itkach** [serokell/tezos-packaging#215]
# Description

Old version of tezos-node keeps running after update

# To Reproduce

- install version 9.1 of package tezos-baking
- start service tezos-node-mainnet
- verify tezos node 9.1 is running  with `curl http://localhost:8732/version`
- upgrade to version 9.2
- confirm with curl 9.1 is still running
- restart tezos-node-mainnet, confirm version 9.2 is now running

# Expected behavior

New version of service is running after upgrade without user having to restart it manually

# Environment

- Ubuntu 18.04

# Additional context

**Comment by pasqu4le** [comment]
confirming the same behavior on `20.04` BTW

**Comment by rvem** [comment]
Fixed in `9.2-0ubuntu2` packages
