### ISSUE TITLE
Update tezos/tezos revisions automatically

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-packaging#26]
# Clarification and motivation

**UPDATE**: revisions have been updated several times, but we want to automate this process.

We are using the following revisions of `tezos/tezos`:
* 94f779a7 for mainnet
* b8731913 for babylonnet

The first one is quite old, it's from October. The second one is even older (September).

We should update them because they are currently old and ideally we want to somehow automate this process to update them from time to time. I propose to update manually and keep this issue open until we automate this process.

# Acceptance criteria

1. ~~`rev`s in `default.nix` are updated to recent ones.~~ ← done
2. (probably later) PRs are automatically created on a regular basis to update these revisions.

**Comment by itkach** [comment]
Release notes should have a link (links) to source code being built, e.g. https://gitlab.com/tezos/tezos/tree/94f779a7

**Comment by gromakovsky** [comment]
@rvem please update to 7.1

**Comment by gromakovsky** [comment]
@rvem please update to 7.2

Also I suppose we can get back to this topic:
> (probably later) PRs are automatically created on a regular basis to update these revisions.

Now `tezos/tezos` has releases with tags. Can we add a scheduled job to CI that would periodically fetch their repo and check whether there is a new tag that starts with `v`? If there is, create a new PR here updating the revision of `tezos/tezos`.

Probably it's not too hard to do :thinking:

**Comment by gromakovsky** [comment]
Note that 7.3 is now available.

**Comment by rvem** [comment]
Now it's a part of #288
