### ISSUE TITLE
Cannot import tezos public key with gpg on linux

### ISSUE THREAD

**Issue by 5472qaywsx** [serokell/tezos-packaging#267]
Am I doing something wrong here? 

Command:
`$ gpg -vvv --debug-all --keyserver http://keys.gnupg.net --search-keys BF847A85AC7BF43E`

Result:
gpg: using character set 'utf-8'
gpg: enabled debug flags: packet mpi crypto filter iobuf memory cache memstat trust hashing ipc clock lookup extprog
gpg: DBG: [not enabled in the source] start
gpg: DBG: chan_3 <- # Home: /home/user/.gnupg
gpg: DBG: chan_3 <- # Config: /home/user/.gnupg/dirmngr.conf
gpg: DBG: chan_3 <- OK Dirmngr 2.2.29 at your service
gpg: DBG: connection to the dirmngr established
gpg: DBG: chan_3 -> GETINFO version
gpg: DBG: chan_3 <- D 2.2.29
gpg: DBG: chan_3 <- OK
gpg: DBG: chan_3 -> KEYSERVER --clear http://keys.gnupg.net
gpg: DBG: chan_3 <- OK
gpg: DBG: chan_3 -> KS_SEARCH -- BF847A85AC7BF43E
gpg: DBG: chan_3 <- S PROGRESS tick ? 0 0
gpg: DBG: chan_3 <- S SOURCE http://pgp.surf.nl:80
gpg: DBG: chan_3 <- ERR 167772218 Dati assenti <Dirmngr>
gpg: data source: http://pgp.surf.nl:80
gpg: chiave "BF847A85AC7BF43E" non trovata nel keyserver
gpg: ricerca nel keyserver fallita: Non trovato
gpg: DBG: chan_3 -> BYE
gpg: DBG: [not enabled in the source] stop
gpg: keydb: handles=0 locks=0 parse=0 get=0
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=0 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=0 cached=0 good=0 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/32768 bytes in 0 blocks

**Comment by kirelagin** [comment]
Hi, can you, please, clarify what exactly you are trying to do and why? What is this key that you are trying to import? I don’t think I recognise it.

**Comment by 5472qaywsx** [comment]
Hi, and thank you for your reply.
What: I was trying to verify the signature of the static binary _binaries-9.5-1.tar.gz_ with the provided signature _binaries-9.5-1.tar.gz.asc_, from page https://github.com/serokell/tezos-packaging/releases/tag/v9.5-1
In the process of verification, I couldn't import the provided key "_0x7EAF9B150ACE940CF8C008A0BF847A85AC7BF43E_" (see above messages).
Why: I was doing this for the sake of security; nevertheless, `sha256sum` check is ok, so what I'm trying here with gpg is probably overkill.

(In a more general way, what I'm trying to do is to get started with tezos, but if I understand it correctly, as I'm not a developer, there is not much I can help with. Why: because I'm curious...)

**Comment by kirelagin** [comment]
Ouch, you are right, thanks for reporting this! Most people we see are running Ubuntu or Red Hat, so we are mostly focused on packages for these distributions, and the binaries on the releases page do not get that much love. It looks like we forgot to upload the key that we use to sign them to the keyservers 🙄. We’ll do this today or tomorrow and you’ll be able to verify the signature, if you want to.

**Comment by pasqu4le** [comment]
Hey there, it looks like `keys.gnupg.net` is not in the best shape, we've now re-uploaded the key to other keyservers.
You can use find it using `http://keyserver.ubuntu.com/`. 

Thanks again for reporting!
