### ISSUE TITLE
Add latest version to Ubuntu PPA (currently ppa has 9.4 whereas the latest release is 9.7)

### ISSUE THREAD

**Issue by mycodecrafting** [serokell/tezos-packaging#272]
Title says it all. Ubuntu PPA is seriously neglected and out of date.

**Comment by itkach** [comment]
Currently builds for Ubuntu depend on Tezos being published to OPAM, and latest tezos in OPAM is 9.4

**Comment by mycodecrafting** [comment]
If there were a sad panda emoji, it would be here. Thanks for the info!

**Comment by UC-VR** [comment]
Hello folks,

very newb question:

is there a way, to somehow existing node v9.4 (on ubuntu) to v9.7?
Either using tezos-setup-wizard 
or some other commands, rather than doing compete reinstall from sctratch using other installation means?

Thanks a lot

**Comment by itkach** [comment]
@UC-VR I think you can just copy [new statically linked tezos binaries](https://github.com/serokell/tezos-packaging/releases/) to `/usr/bin/` (replacing the ones that are already there) and restart tezos services

in the meantime 9.7 debs and rpms are on the way but are currently blocked by https://github.com/ocaml/opam-repository/pull/19237

**Comment by UC-VR** [comment]
Thanks for your reply! This is exactly what I tried yesterday, and it had worked!

Thanks again

Get Outlook for Android<https://aka.ms/AAb9ysg>

**Comment by ixahedron** [comment]
v9.7 native packages for Ubuntu and Fedora have been uploaded to their respective package repositories 🎉
