### ISSUE TITLE
Where can download tezos-Validator  

### ISSUE THREAD

**Issue by Black52** [serokell/tezos-packaging#283]
tezos-node  v10.0 Have downloaded。
How to download tezos-Validator？？

**Comment by Black52** [comment]
Why was it updated after 10.0，Update headers  at 0。Is there a faster way？

**Comment by pasqu4le** [comment]
> How to download tezos-Validator

we don't build a static binary for `tezos-validator`. From [the official documentation](http://tezos.gitlab.io/introduction/howtouse.html#validator):
> It is not meant to be invoked directly by users.

As you can see from the [tezos/tezos releases](https://gitlab.com/tezos/tezos/-/releases) a binary for `tezos-validator` is not included in releases either (for example [10.0.0](https://gitlab.com/tezos/tezos/-/releases/10.0.0)), but can be found in RCs (for example [10.0~rc3](https://gitlab.com/tezos/tezos/-/releases/v10.0-rc3)) in a _Other > Static binaries_ link.

Do you have a use case for the binary itself?

**Comment by Black52** [comment]
> > 如何下载 tezos-Validator
> 
> 我们不会为`tezos-validator`. 从[官方文档](http://tezos.gitlab.io/introduction/howtouse.html#validator)：
> 
> > 它并不意味着由用户直接调用。
> 
> 正如您从[tezos/tezos 版本中](https://gitlab.com/tezos/tezos/-/releases)看到的，[发行版](https://gitlab.com/tezos/tezos/-/releases)`tezos-validator`中也不包含二进制文件（例如[10.0.0](https://gitlab.com/tezos/tezos/-/releases/10.0.0)），但可以在 RCs（例如[10.0~rc3](https://gitlab.com/tezos/tezos/-/releases/v10.0-rc3)）中的_其他 > 静态二进制文件_链接中找到。
> 
> 你有二进制文件本身的用例吗？

**Comment by Black52** [comment]
> > How to download tezos-Validator
> 
> we don't build a static binary for `tezos-validator`. From [the official documentation](http://tezos.gitlab.io/introduction/howtouse.html#validator):
> 
> > It is not meant to be invoked directly by users.
> 
> As you can see from the [tezos/tezos releases](https://gitlab.com/tezos/tezos/-/releases) a binary for `tezos-validator` is not included in releases either (for example [10.0.0](https://gitlab.com/tezos/tezos/-/releases/10.0.0)), but can be found in RCs (for example [10.0~rc3](https://gitlab.com/tezos/tezos/-/releases/v10.0-rc3)) in a _Other > Static binaries_ link.
> 
> Do you have a use case for the binary itself?

The tezos-Validator downloaded from here does not work directly. What if I use version 10.0 for tezos-node and version 9.6 for Tezos-Validator?
