### ISSUE TITLE
Build everything for carthagennet, research the difference

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-packaging#30]
# Clarification and motivation

Carthagennet network is alive. I am not sure whether it is running Cartage protocol, but most likely it does, and even if it does not, it most likely will soon. So we should build stuff for carthagennet as well. There is a corresponding branch: https://gitlab.com/tezos/tezos/commits/carthagenet

However, it is not clear whether there is any substantial differences between these branches and whether they are compatible. I heard that genesis public key is embedded into code, so that's one of the reasons why branches can be incompatible. But I suppose it applies only to a subset of executables, not to all of them. I also heard that Tezos developers want to stop having per-network branches, but I don't know any details.

With three networks number of assets becomes quite large, so we should decrease it if possible.

# Acceptance criteria

1. Everything we build should be built not only for mainnet and babylonnet, but also carthagennet.
2. Figure out the difference between branches and whether we can decrease number of assets. Ideally also figure out some details about getting rid of per-network branches (maybe ask in tezos-dev).

**Comment by rvem** [comment]
`tezos-client` version from carthagenet is compatible with all three versions of `tezos-node`, however it has a mention of `carthagenet` in the disclaimer, so I think it's okay to provide only the latest version of tezos-client (from carthagenet branch)

**Comment by rvem** [comment]
https://tezos-dev.slack.com/archives/CAK69LDGE/p1580994264078200
> The mainnet, carthagenet, babylonnet and zeronet branches are network-specific. But the master branch is now capable of running all of those networks (well, except that it cannot bake on zeronet). This is true for both tezos-node and tezos-client. See http://tezos.gitlab.io/user/multinetwork.html for more information.
The baker, endorser and accuser binaries however are protocol-specific. This is why their name contains the protocol name. The master branch comes with one baker / endorser / accuser for each protocol, and you run the one(s) that are needed for the network you connect to.

So, apparently, we can just build everything from the master branch
