### ISSUE TITLE
tezos-node --version Instruction non permise (core dumped)

### ISSUE THREAD

**Issue by azerlos** [serokell/tezos-packaging#342]
# Description

# To Reproduce

sudo apt-get install -y tezos-node
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Les NOUVEAUX paquets suivants seront installés :
  tezos-node
0 mis à jour, 1 nouvellement installés, 0 à enlever et 324 non mis à jour.
Il est nécessaire de prendre 19,8 Mo dans les archives.
Après cette opération, 116 Mo d'espace disque supplémentaires seront utilisés.
Réception de :1 http://ppa.launchpad.net/serokell/tezos/ubuntu focal/main amd64 tezos-node amd64 2:11.0-0ubuntu1~focal [19,8 MB]
19,8 Mo réceptionnés en 2s (10,2 Mo/s)   
Sélection du paquet tezos-node précédemment désélectionné.
(Lecture de la base de données... 196738 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../tezos-node_2%3a11.0-0ubuntu1~focal_amd64.deb ...
Dépaquetage de tezos-node (2:11.0-0ubuntu1~focal) ...
Paramétrage de tezos-node (2:11.0-0ubuntu1~focal) ...
Illegal instruction (core dumped)
dpkg: erreur de traitement du paquet tezos-node (--configure) :
 installed tezos-node package post-installation script subprocess returned error exit status 132
Des erreurs ont été rencontrées pendant l'exécution :
 tezos-node
E: Sub-process /usr/bin/dpkg returned an error code (1)

tezos-node --version
Instruction non permise (core dumped)

# Expected behavior

# Environment

- ubuntu
- 20.04.2 LTS

# Additional context

fresh install ubuntu

**Comment by pasqu4le** [comment]
This sadly seems to be a known issue, see [tezos/#1788](https://gitlab.com/tezos/tezos/-/issues/1788).

The summary is that some relatively recent processor instructions are used by the build process, which makes some (generally older) architectures unsupported.

We are trying to understand if we can fix this on the packaging side, but in the meanwhile I would recommend commenting on the upstream issue I mentioned above, to give it more visibility.

**Comment by vivienbcr** [comment]
I have same problem when i'm trying to update my baking node to v11 with serokell packaging. I've comment it on tezos gitlab.

**Comment by vivienbcr** [comment]
Tezos have deploy alternative for docker users https://hub.docker.com/layers/tezos/tezos/v11.0_no_adx/images/sha256-b0532eb8cc4201983e24034cf5252992db5c99bb0f7cb10afd1bf4675153ea4a?context=explore . 
Maybe we can have same result with serokell build and wizard ?

**Comment by rvem** [comment]
@vivienbcr, we've published packages that are based on `v11+no_adx` Octez tag (though, some packages for ARM are still building). Let us know if they work for you

**Comment by azerlos** [comment]
I've install the last  release  v11.0+no_adx-1 Latest . https://github.com/serokell/tezos-packaging/releases
it's looks work well for me .
tezos-node --version 
d43f7230 (2021-11-21 22:28:42 +0100) (11.0)

Thank you
