### ISSUE TITLE
The synchronization cannot continue after the synchronization height reaches 1916927

### ISSUE THREAD

**Issue by Black52** [serokell/tezos-packaging#348]
version:v11.0+no_adx-1
My startup command：nohup /data/tezos-11.0+no_adx-1/tezos-node run --rpc-addr=0.0.0.0:9755 --config-file=/root/.tezos-node/config.json --data-dir=/data/tezos-data --history-mode full --network=mainnet &
I used snapshot synchronization again. There was no problem at first. When the altitude reached 1916927, I couldn't continue to synchronize

**Comment by Black52** [comment]
`Dec  4 19:50:02.921 - node.config.validation: the node configuration has been successfully validated.
Dec  4 19:50:02.922 - node.main: read identity file (peer_id = idsevLjMV2oBgAT9RE89YBfXJqdLuS)
Dec  4 19:50:02.922 - node.main: starting the Tezos node (chain = TEZOS_MAINNET)
Dec  4 19:50:02.922 - node.main: disabled local peer discovery
Dec  4 19:50:02.923 - node: shell-node initialization: bootstrapping
Dec  4 19:50:02.976 - node: shell-node initialization: p2p_maintain_started
Dec  4 19:50:02.976 - external_block_validator: initialized
Dec  4 19:50:03.934 - external_block_validator: block validator process started with pid 887714
Dec  4 19:50:27.354 - node.validator: activate chain NetXdQprcVkpaWU
Dec  4 19:50:27.355 - p2p.maintenance: too few connections (0)
Dec  4 19:50:27.355 - validator.chain: Sync_status: unsync
Dec  4 19:50:27.355 - node.main: starting RPC server on ::ffff:0.0.0.0:9755 (tls = false)
Dec  4 19:50:27.355 - node.main: the Tezos node is now running
Dec  4 19:50:30.095 - node.validator.bootstrap_pipeline: fetching branch of about 304 blocks from peer idrW2XzDsfv7vd2JWRDZLpQD75CzR9
Dec  4 19:50:30.095 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:31.854 - node.validator.bootstrap_pipeline: fetching branch of about 321 blocks from peer idt6fQPMXLt4t1rWx4inv8rXhk9on9
Dec  4 19:50:31.854 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:50:33.148 - node.validator.bootstrap_pipeline: fetching branch of about 314 blocks from peer idtgiAkGH9abdGXurJV8npYv7JXicd
Dec  4 19:50:33.148 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:50:34.543 - node.validator.bootstrap_pipeline: fetching branch of about 305 blocks from peer idqrAxbd42bQ6T8ojYrAcVWLkSmBeG
Dec  4 19:50:34.543 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:35.404 - node.validator.bootstrap_pipeline: fetching branch of about 309 blocks from peer ids9NprCRqmfpVZ2Yduy2XuqMWpoV7
Dec  4 19:50:35.404 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:50:36.457 - node.validator.bootstrap_pipeline: fetching branch of about 312 blocks from peer idsJGLZnpURqnpDJETNY7psy8n9UL8
Dec  4 19:50:36.457 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:37.908 - node.validator.bootstrap_pipeline: fetching branch of about 307 blocks from peer idqZnFMYFR43JM5hrFwRgTcw89kbwL
Dec  4 19:50:37.908 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:50:38.143 - node.validator.bootstrap_pipeline: fetching branch of about 321 blocks from peer idthKQsSphkG2FxMuQsM9Cf6dXjZ6A
Dec  4 19:50:38.143 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:38.985 - node.validator.bootstrap_pipeline: fetching branch of about 306 blocks from peer idtnW2Hr6yAfQnYbYpt4FgvVBv8eqn
Dec  4 19:50:38.985 - node.validator.bootstrap_pipeline:   in 47 steps
Dec  4 19:50:39.731 - node.validator.bootstrap_pipeline: fetching branch of about 356 blocks from peer idrWeKEtNo2oY9XvBL9jevcVKzZ7zx
Dec  4 19:50:39.731 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:50:39.747 - node.validator.bootstrap_pipeline: fetching branch of about 313 blocks from peer idtZ6QQpme5W3R2GsnVQG1WZ59pyfQ
Dec  4 19:50:39.747 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:41.120 - node.validator.bootstrap_pipeline: fetching branch of about 338 blocks from peer idsoidVsG59Un8Wvc25UjWd91dYb39
Dec  4 19:50:41.120 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:50:41.758 - node.validator.bootstrap_pipeline: fetching branch of about 326 blocks from peer idrAAdusy7xocMhr7DxNJ7SJjhqCpD
Dec  4 19:50:41.758 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:50:42.497 - node.validator.bootstrap_pipeline: fetching branch of about 307 blocks from peer idthwLvgb9vrnznSRcZWr5eJ3eqJKB
Dec  4 19:50:42.497 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:42.637 - node.validator.bootstrap_pipeline: fetching branch of about 364 blocks from peer idqepPvvtUkGJZQdMDNU9VLBwJTKeV
Dec  4 19:50:42.637 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:50:53.562 - node.validator.bootstrap_pipeline: fetching branch of about 314 blocks from peer idrqewsCjt7r7j54QGmRKAamwWhcZb
Dec  4 19:50:53.562 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:56.049 - node.validator.bootstrap_pipeline: fetching branch of about 333 blocks from peer idrk3x7AogxAZypz9c3PktmYW66bAP
Dec  4 19:50:56.049 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:50:56.338 - node.validator.bootstrap_pipeline: fetching branch of about 333 blocks from peer idsPxh31tcsYZDHHTeDQKkcx8LuR1V
Dec  4 19:50:56.338 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:50:57.965 - node.validator.bootstrap_pipeline: fetching branch of about 312 blocks from peer idrAevruyAV9cqDnrqYTkTw1DtsY4R
Dec  4 19:50:57.965 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:58.416 - node.validator.bootstrap_pipeline: fetching branch of about 4 blocks from peer idqyvw3M69QmLNgPM7r8pnZdjuyJGK in
Dec  4 19:50:58.416 - node.validator.bootstrap_pipeline:   3 steps
Dec  4 19:50:58.726 - node.validator.bootstrap_pipeline: fetching branch of about 321 blocks from peer idsJmj8PGzxLtxULXG3jmVtAkjDvN4
Dec  4 19:50:58.726 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:59.991 - node.validator.bootstrap_pipeline: fetching branch of about 344 blocks from peer ids1oWdcUkP3PR4MS6WS9YAwEnHzkE
Dec  4 19:50:59.991 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:51:01.058 - node.validator.bootstrap_pipeline: fetching branch of about 2 blocks from peer ids3nDEEpb9WsAqA3aSie3xFUXqkSi in
Dec  4 19:51:01.058 - node.validator.bootstrap_pipeline:   1 steps
Dec  4 19:51:01.867 - node.validator.bootstrap_pipeline: fetching branch of about 317 blocks from peer ids8idfXZfrvA7hgQdiEErgikN4XUX
Dec  4 19:51:01.867 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:01.870 - validation: initializing protocol PtHangz2aRng...
Dec  4 19:51:01.870 - node.protocol: 011-PtHangz2: flattening the context storage: this operation may take several minutes
Dec  4 19:51:01.940 - node.validator.bootstrap_pipeline: fetching branch of about 347 blocks from peer idsrxm9uU8ZV7RYRE2pq1392vhhYmp
Dec  4 19:51:01.940 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:02.824 - node.validator.bootstrap_pipeline: fetching branch of about 317 blocks from peer idqs26xkJcqTs4GcxKsb1PyxfoHXZA
Dec  4 19:51:02.824 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:51:13.526 - node.validator.bootstrap_pipeline: fetching branch of about 329 blocks from peer idqq7zaXLhtoJCtRoZCLKVF9kAZ9h4
Dec  4 19:51:13.526 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:14.190 - node.validator.bootstrap_pipeline: fetching branch of about 317 blocks from peer idtoLqGPS8MmjiFZ4yAMXN9jvNeSek
Dec  4 19:51:14.190 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:14.756 - node.validator.bootstrap_pipeline: fetching branch of about 318 blocks from peer idrTHJvsMcAmgaFBMUeYBVCt5nTye1
Dec  4 19:51:14.756 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:51:15.341 - node.validator.bootstrap_pipeline: fetching branch of about 350 blocks from peer idrgaTDHzLb7DzMnQncRib8oxEACTP
Dec  4 19:51:15.341 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:17.372 - node.validator.bootstrap_pipeline: fetching branch of about 339 blocks from peer idrxBrNuUMRNCmf58YFBYH26WKWUKT
Dec  4 19:51:17.372 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:17.784 - node.validator.bootstrap_pipeline: fetching branch of about 307 blocks from peer idrs9vYV6rqJc6NTAkygsw5VqzSNnf
Dec  4 19:51:17.784 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:18.077 - node.validator.bootstrap_pipeline: fetching branch of about 306 blocks from peer idsBH5fy8obfQUT9TbgQxNwtBKQUze
Dec  4 19:51:18.077 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:51:18.353 - node.validator.bootstrap_pipeline: fetching branch of about 345 blocks from peer idszYrtEKvwwH8vnCwpRwzhZgRcQ7e
Dec  4 19:51:18.353 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:18.797 - node.validator.bootstrap_pipeline: fetching branch of about 313 blocks from peer idtvptTtWb13Xm3ak99WhsDughqRF3
Dec  4 19:51:18.797 - node.validator.bootstrap_pipeline:   in 47 steps
Dec  4 19:51:18.852 - node.validator.bootstrap_pipeline: fetching branch of about 348 blocks from peer idqaNEGuucYmqC9p5R75YQbkEciVn2
Dec  4 19:51:18.852 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:19.783 - node.validator.bootstrap_pipeline: fetching branch of about 366 blocks from peer idtQ13rSBYu4cBGVupKRgXQDryy6NR
Dec  4 19:51:19.783 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:51:20.142 - node.validator.bootstrap_pipeline: fetching branch of about 329 blocks from peer idrBUMvTLe775pCA5CiQ98VUuR6ADG
Dec  4 19:51:20.142 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:20.410 - node.validator.bootstrap_pipeline: fetching branch of about 299 blocks from peer idt3hrZezsBviHo3jeGK7RrEKHU81b
Dec  4 19:51:20.410 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:51:21.693 - node.validator.bootstrap_pipeline: fetching branch of about 301 blocks from peer idrQLLyuPCcQpwefqXXvUFoeef45Ve
Dec  4 19:51:21.693 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:21.795 - node.validator.bootstrap_pipeline: fetching branch of about 313 blocks from peer idqa27jvjNcBLWHebwG2iHPNbYtszj
Dec  4 19:51:21.795 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:22.717 - node.validator.bootstrap_pipeline: fetching branch of about 333 blocks from peer idsgFeHtbvFcMtEncjPovi31ee12di
Dec  4 19:51:22.717 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:23.277 - node.validator.bootstrap_pipeline: fetching branch of about 324 blocks from peer idsU2yuoVRqCjdnRQNrAjp6muqe1Kc
Dec  4 19:51:23.277 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:23.746 - node.validator.bootstrap_pipeline: fetching branch of about 305 blocks from peer idsEYvNr1khqYFPXiJ2uh1rG75qUjB
Dec  4 19:51:23.746 - node.validator.bootstrap_pipeline:   in 47 steps
Dec  4 19:51:24.466 - node.validator.bootstrap_pipeline: fetching branch of about 323 blocks from peer idtU9QiU8zKvJ67vao1rTDkVwe6myw
Dec  4 19:51:24.466 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:51:25.534 - node.validator.bootstrap_pipeline: fetching branch of about 322 blocks from peer idsxuJrLjswBMUizAHqcaE36UmBfsY
Dec  4 19:51:25.534 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:36.454 - node.validator.bootstrap_pipeline: fetching branch of about 312 blocks from peer idrVFqMYMyyjBLSFU2HCS3QNXGVNtZ
Dec  4 19:51:36.454 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:37.124 - node.validator.bootstrap_pipeline: fetching branch of about 317 blocks from peer idsTwirirpzLH2ZdF44r9Kg2j6xJ5z
Dec  4 19:51:37.124 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:57:05.863 - node.validator.bootstrap_pipeline: fetching branch of about 350 blocks from peer idsMdRxoJQxvGXchVL4dhZtPKdg318
Dec  4 19:57:05.863 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:58:26.518 - node.validator.bootstrap_pipeline: fetching branch of about 335 blocks from peer idrdWRSh8tLkip3PbuaDu4Z5sSXua2
Dec  4 19:58:26.518 - node.validator.bootstrap_pipeline:   in 50 steps
`

**Comment by Black52** [comment]
_Dec  4 19:50:02.921 - node.config.validation: the node configuration has been successfully validated.
Dec  4 19:50:02.922 - node.main: read identity file (peer_id = idsevLjMV2oBgAT9RE89YBfXJqdLuS)
Dec  4 19:50:02.922 - node.main: starting the Tezos node (chain = TEZOS_MAINNET)
Dec  4 19:50:02.922 - node.main: disabled local peer discovery
Dec  4 19:50:02.923 - node: shell-node initialization: bootstrapping
Dec  4 19:50:02.976 - node: shell-node initialization: p2p_maintain_started
Dec  4 19:50:02.976 - external_block_validator: initialized
Dec  4 19:50:03.934 - external_block_validator: block validator process started with pid 887714
Dec  4 19:50:27.354 - node.validator: activate chain NetXdQprcVkpaWU
Dec  4 19:50:27.355 - p2p.maintenance: too few connections (0)
Dec  4 19:50:27.355 - validator.chain: Sync_status: unsync
Dec  4 19:50:27.355 - node.main: starting RPC server on ::ffff:0.0.0.0:9755 (tls = false)
Dec  4 19:50:27.355 - node.main: the Tezos node is now running
Dec  4 19:50:30.095 - node.validator.bootstrap_pipeline: fetching branch of about 304 blocks from peer idrW2XzDsfv7vd2JWRDZLpQD75CzR9
Dec  4 19:50:30.095 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:31.854 - node.validator.bootstrap_pipeline: fetching branch of about 321 blocks from peer idt6fQPMXLt4t1rWx4inv8rXhk9on9
Dec  4 19:50:31.854 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:50:33.148 - node.validator.bootstrap_pipeline: fetching branch of about 314 blocks from peer idtgiAkGH9abdGXurJV8npYv7JXicd
Dec  4 19:50:33.148 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:50:34.543 - node.validator.bootstrap_pipeline: fetching branch of about 305 blocks from peer idqrAxbd42bQ6T8ojYrAcVWLkSmBeG
Dec  4 19:50:34.543 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:35.404 - node.validator.bootstrap_pipeline: fetching branch of about 309 blocks from peer ids9NprCRqmfpVZ2Yduy2XuqMWpoV7
Dec  4 19:50:35.404 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:50:36.457 - node.validator.bootstrap_pipeline: fetching branch of about 312 blocks from peer idsJGLZnpURqnpDJETNY7psy8n9UL8
Dec  4 19:50:36.457 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:37.908 - node.validator.bootstrap_pipeline: fetching branch of about 307 blocks from peer idqZnFMYFR43JM5hrFwRgTcw89kbwL
Dec  4 19:50:37.908 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:50:38.143 - node.validator.bootstrap_pipeline: fetching branch of about 321 blocks from peer idthKQsSphkG2FxMuQsM9Cf6dXjZ6A
Dec  4 19:50:38.143 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:38.985 - node.validator.bootstrap_pipeline: fetching branch of about 306 blocks from peer idtnW2Hr6yAfQnYbYpt4FgvVBv8eqn
Dec  4 19:50:38.985 - node.validator.bootstrap_pipeline:   in 47 steps
Dec  4 19:50:39.731 - node.validator.bootstrap_pipeline: fetching branch of about 356 blocks from peer idrWeKEtNo2oY9XvBL9jevcVKzZ7zx
Dec  4 19:50:39.731 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:50:39.747 - node.validator.bootstrap_pipeline: fetching branch of about 313 blocks from peer idtZ6QQpme5W3R2GsnVQG1WZ59pyfQ
Dec  4 19:50:39.747 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:41.120 - node.validator.bootstrap_pipeline: fetching branch of about 338 blocks from peer idsoidVsG59Un8Wvc25UjWd91dYb39
Dec  4 19:50:41.120 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:50:41.758 - node.validator.bootstrap_pipeline: fetching branch of about 326 blocks from peer idrAAdusy7xocMhr7DxNJ7SJjhqCpD
Dec  4 19:50:41.758 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:50:42.497 - node.validator.bootstrap_pipeline: fetching branch of about 307 blocks from peer idthwLvgb9vrnznSRcZWr5eJ3eqJKB
Dec  4 19:50:42.497 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:42.637 - node.validator.bootstrap_pipeline: fetching branch of about 364 blocks from peer idqepPvvtUkGJZQdMDNU9VLBwJTKeV
Dec  4 19:50:42.637 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:50:53.562 - node.validator.bootstrap_pipeline: fetching branch of about 314 blocks from peer idrqewsCjt7r7j54QGmRKAamwWhcZb
Dec  4 19:50:53.562 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:56.049 - node.validator.bootstrap_pipeline: fetching branch of about 333 blocks from peer idrk3x7AogxAZypz9c3PktmYW66bAP
Dec  4 19:50:56.049 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:50:56.338 - node.validator.bootstrap_pipeline: fetching branch of about 333 blocks from peer idsPxh31tcsYZDHHTeDQKkcx8LuR1V
Dec  4 19:50:56.338 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:50:57.965 - node.validator.bootstrap_pipeline: fetching branch of about 312 blocks from peer idrAevruyAV9cqDnrqYTkTw1DtsY4R
Dec  4 19:50:57.965 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:58.416 - node.validator.bootstrap_pipeline: fetching branch of about 4 blocks from peer idqyvw3M69QmLNgPM7r8pnZdjuyJGK in
Dec  4 19:50:58.416 - node.validator.bootstrap_pipeline:   3 steps
Dec  4 19:50:58.726 - node.validator.bootstrap_pipeline: fetching branch of about 321 blocks from peer idsJmj8PGzxLtxULXG3jmVtAkjDvN4
Dec  4 19:50:58.726 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:50:59.991 - node.validator.bootstrap_pipeline: fetching branch of about 344 blocks from peer ids1oWdcUkP3PR4MS6WS9YAwEnHzkE
Dec  4 19:50:59.991 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:51:01.058 - node.validator.bootstrap_pipeline: fetching branch of about 2 blocks from peer ids3nDEEpb9WsAqA3aSie3xFUXqkSi in
Dec  4 19:51:01.058 - node.validator.bootstrap_pipeline:   1 steps
Dec  4 19:51:01.867 - node.validator.bootstrap_pipeline: fetching branch of about 317 blocks from peer ids8idfXZfrvA7hgQdiEErgikN4XUX
Dec  4 19:51:01.867 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:01.870 - validation: initializing protocol PtHangz2aRng...
Dec  4 19:51:01.870 - node.protocol: 011-PtHangz2: flattening the context storage: this operation may take several minutes
Dec  4 19:51:01.940 - node.validator.bootstrap_pipeline: fetching branch of about 347 blocks from peer idsrxm9uU8ZV7RYRE2pq1392vhhYmp
Dec  4 19:51:01.940 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:02.824 - node.validator.bootstrap_pipeline: fetching branch of about 317 blocks from peer idqs26xkJcqTs4GcxKsb1PyxfoHXZA
Dec  4 19:51:02.824 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:51:13.526 - node.validator.bootstrap_pipeline: fetching branch of about 329 blocks from peer idqq7zaXLhtoJCtRoZCLKVF9kAZ9h4
Dec  4 19:51:13.526 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:14.190 - node.validator.bootstrap_pipeline: fetching branch of about 317 blocks from peer idtoLqGPS8MmjiFZ4yAMXN9jvNeSek
Dec  4 19:51:14.190 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:14.756 - node.validator.bootstrap_pipeline: fetching branch of about 318 blocks from peer idrTHJvsMcAmgaFBMUeYBVCt5nTye1
Dec  4 19:51:14.756 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:51:15.341 - node.validator.bootstrap_pipeline: fetching branch of about 350 blocks from peer idrgaTDHzLb7DzMnQncRib8oxEACTP
Dec  4 19:51:15.341 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:17.372 - node.validator.bootstrap_pipeline: fetching branch of about 339 blocks from peer idrxBrNuUMRNCmf58YFBYH26WKWUKT
Dec  4 19:51:17.372 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:17.784 - node.validator.bootstrap_pipeline: fetching branch of about 307 blocks from peer idrs9vYV6rqJc6NTAkygsw5VqzSNnf
Dec  4 19:51:17.784 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:18.077 - node.validator.bootstrap_pipeline: fetching branch of about 306 blocks from peer idsBH5fy8obfQUT9TbgQxNwtBKQUze
Dec  4 19:51:18.077 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:51:18.353 - node.validator.bootstrap_pipeline: fetching branch of about 345 blocks from peer idszYrtEKvwwH8vnCwpRwzhZgRcQ7e
Dec  4 19:51:18.353 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:18.797 - node.validator.bootstrap_pipeline: fetching branch of about 313 blocks from peer idtvptTtWb13Xm3ak99WhsDughqRF3
Dec  4 19:51:18.797 - node.validator.bootstrap_pipeline:   in 47 steps
Dec  4 19:51:18.852 - node.validator.bootstrap_pipeline: fetching branch of about 348 blocks from peer idqaNEGuucYmqC9p5R75YQbkEciVn2
Dec  4 19:51:18.852 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:19.783 - node.validator.bootstrap_pipeline: fetching branch of about 366 blocks from peer idtQ13rSBYu4cBGVupKRgXQDryy6NR
Dec  4 19:51:19.783 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:51:20.142 - node.validator.bootstrap_pipeline: fetching branch of about 329 blocks from peer idrBUMvTLe775pCA5CiQ98VUuR6ADG
Dec  4 19:51:20.142 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:20.410 - node.validator.bootstrap_pipeline: fetching branch of about 299 blocks from peer idt3hrZezsBviHo3jeGK7RrEKHU81b
Dec  4 19:51:20.410 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:51:21.693 - node.validator.bootstrap_pipeline: fetching branch of about 301 blocks from peer idrQLLyuPCcQpwefqXXvUFoeef45Ve
Dec  4 19:51:21.693 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:21.795 - node.validator.bootstrap_pipeline: fetching branch of about 313 blocks from peer idqa27jvjNcBLWHebwG2iHPNbYtszj
Dec  4 19:51:21.795 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:22.717 - node.validator.bootstrap_pipeline: fetching branch of about 333 blocks from peer idsgFeHtbvFcMtEncjPovi31ee12di
Dec  4 19:51:22.717 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:23.277 - node.validator.bootstrap_pipeline: fetching branch of about 324 blocks from peer idsU2yuoVRqCjdnRQNrAjp6muqe1Kc
Dec  4 19:51:23.277 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:23.746 - node.validator.bootstrap_pipeline: fetching branch of about 305 blocks from peer idsEYvNr1khqYFPXiJ2uh1rG75qUjB
Dec  4 19:51:23.746 - node.validator.bootstrap_pipeline:   in 47 steps
Dec  4 19:51:24.466 - node.validator.bootstrap_pipeline: fetching branch of about 323 blocks from peer idtU9QiU8zKvJ67vao1rTDkVwe6myw
Dec  4 19:51:24.466 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:51:25.534 - node.validator.bootstrap_pipeline: fetching branch of about 322 blocks from peer idsxuJrLjswBMUizAHqcaE36UmBfsY
Dec  4 19:51:25.534 - node.validator.bootstrap_pipeline:   in 50 steps
Dec  4 19:51:36.454 - node.validator.bootstrap_pipeline: fetching branch of about 312 blocks from peer idrVFqMYMyyjBLSFU2HCS3QNXGVNtZ
Dec  4 19:51:36.454 - node.validator.bootstrap_pipeline:   in 49 steps
Dec  4 19:51:37.124 - node.validator.bootstrap_pipeline: fetching branch of about 317 blocks from peer idsTwirirpzLH2ZdF44r9Kg2j6xJ5z
Dec  4 19:51:37.124 - node.validator.bootstrap_pipeline:   in 48 steps
Dec  4 19:57:05.863 - node.validator.bootstrap_pipeline: fetching branch of about 350 blocks from peer idsMdRxoJQxvGXchVL4dhZtPKdg318
Dec  4 19:57:05.863 - node.validator.bootstrap_pipeline:   in 51 steps
Dec  4 19:58:26.518 - node.validator.bootstrap_pipeline: fetching branch of about 335 blocks from peer idrdWRSh8tLkip3PbuaDu4Z5sSXua2
Dec  4 19:58:26.518 - node.validator.bootstrap_pipeline:   in 50 steps
_

**Comment by Black52** [comment]
_Dec  4 20:13:10.701 - node.protocol: 011-PtHangz2: context storage flattening completed
Dec  4 20:13:39.540 - validator.chain: Sync_status: stuck
Dec  4 20:13:39.975 - validator.chain: Chain is bootstrapped
_

**Comment by ixahedron** [comment]
Hi! Getting stuck after 1916927 was to be expected: several hours ago, a protocol switch took place on mainnet that required context flattening. This takes some time, sometimes up to an hour.

But I see your flattening has been completed – has the issue been resolved since? Have you been able to sync past 1916927? If not, I would suggest importing a snapshot created after the switch, i.e. containing 1916928 in it. It seems they are already available [here](https://mainnet.xtz-shots.io/).

**Comment by Black52** [comment]
> 你好！在 1916927 之后卡住是意料之中的：几个小时前，主网上发生了一个需要上下文扁平化的协议切换。这需要一些时间，有时长达一个小时。
> 
> 但是我看到你的扁平化已经完成——这个问题已经解决了吗？你能同步过去 1916927 吗？如果没有，我建议导入在切换后创建的快照，即其中包含 1916928。似乎它们已经[在此处](https://mainnet.xtz-shots.io/)可用。

I downloaded this snapshot and imported it to 20% and it was automatically killed

Dec  4 21:24:19.730 - node.snapshots: importing data from snapshot
Dec  4 21:24:19.730 - node.snapshots:   /data/bak/mainnet_20211204-033906_BMdswT4dZGGzntLhKiCfGvWUNYWYtNzhqZjGDdDgL4GrBjbG5gg.full: chain TEZOS_MAINNET, block hash BMdswT4dZGGzntLhKiCfGvWUNYWYtNzhqZjGDdDgL4GrBjbG5gg at level 1916930 in full (snapshot version 2)
Dec  4 21:24:19.731 - node.snapshots: retrieving and validating data. This can take a while, please bear with us
Writing context: 2377K/11447K (20%) elements, 401MiB read...Killed

**Comment by ixahedron** [comment]
This sounds like an "Out of memory" issue, where RAM consumed by the node exceeds its limits and the process is killed by the OS. You can try to increase swap to extend memory available.

**Comment by ixahedron** [comment]
Hi @Black52! Have you since resolved this issue?

**Comment by pasqu4le** [comment]
I'm closing this issue as this protocol activation is now long in the past.

Feel free to reopen it if this problem persisted after that for some reason.
