### ISSUE TITLE
[BUG] tezos-setup-wizard offers wrong list of addresses when two Ledger devices are connected

### ISSUE THREAD

**Issue by itkach** [serokell/tezos-packaging#379]
# Description

When setting up baking with ledger and 2 ledger devices are plugged in, only one device is listed, but the list of 4 available addresses is duplicated:

```
How do you want to import the baker key?
1. ledger (default)            From a ledger
2. secret-key                  Either the unencrypted or password-encrypted secret key for
                               your address
3. json                        Faucet JSON file from https://faucet.tzalpha.net/
> 1
Please open the Tezos Baking app on your ledger.
Select a key to import from ledger://crouching-tiger-hidden-dragon/.
You can choose one of the suggested derivations or provide your own:
1. bip25519/0h/0h,  address: tz1...A, balance: 0 ꜩ
2. ed25519/0h/0h,   address: tz1...B, balance: 0 ꜩ
3. secp256k1/0h/0h, address: tz2...C, balance: 0 ꜩ
4. P-256/0h/0h,     address: tz3...D, balance: 0 ꜩ
5. bip25519/0h/0h,  address: tz1...A, balance: 0 ꜩ
6. ed25519/0h/0h,   address: tz1...B, balance: 0 ꜩ
7. secp256k1/0h/0h, address: tz2...C, balance: 0 ꜩ
8. P-256/0h/0h,     address: tz3...D, balance: 0 ꜩ
9. Specify derivation path
10. Go back
```

# To Reproduce

- Plug-in 2 ledger devices and start tezos baking app on both
- Follow tezos-setup-wizard
- In the import key step, choose ledger, observe second ledger is not listed, addresses from the first device are duplicated 

# Expected behavior

Both devices are listed, with some addresses from each, like so:
```
You can choose one of the suggested derivations or provide your own.

From ledger://crouching-tiger-hidden-dragon/:

1. bip25519/0h/0h,  address: tz1...A, balance: 0 ꜩ
2. ed25519/0h/0h,   address: tz1...B, balance: 0 ꜩ
3. secp256k1/0h/0h, address: tz2...C, balance: 0 ꜩ
4. P-256/0h/0h,     address: tz3...D, balance: 0 ꜩ
5. Specify derivation path

From: ledger://flat-crocodile-toy-cheburashka:

6. bip25519/0h/0h,  address: tz1...E, balance: 0 ꜩ
7. ed25519/0h/0h,   address: tz1...F, balance: 0 ꜩ
8. secp256k1/0h/0h, address: tz2...G, balance: 0 ꜩ
9. P-256/0h/0h,     address: tz3...H, balance: 0 ꜩ
10. Specify derivation path

11. Go back
```

or introduce intermediate step to select one of multiple ledgers before proceeding to address/derivation path selection

# Environment

- OS: Ubuntu 18.04
- branch/revision: 12.0-rc2

# Additional context

One ledger device is set up with Kiln, another with tezos-packaging. Kiln node uses different ports and different locations for data and config so it should be possible to use both at the same time on the same machine, baking on the same or different networks

**Comment by rvem** [comment]
Resolved in `v12.0-1`
