### ISSUE TITLE
[BUG] tezos-voting-wizard requires tezos-baking-mainnet service

### ISSUE THREAD

**Issue by itkach** [serokell/tezos-packaging#401]
# Description

tezos-voting-wizard refuses to run without tezos-baking-mainnet service. The only actual requirement for voting is access to ledger device with wallet app running via tezos-client. 

# To Reproduce

- run tezos-voting-wizard
- select "mainnet"
- observe tezos-voting-wizard exits after displaying the following message:

```
Looks like the tezos-baking-mainnet service isn't running.
Please start the service or set up baking.
You can do this by running:
tezos-setup-wizard
```

# Expected behavior

tezos-voting-wizard works on any machine where tezos-client is installed

# Environment

- OS: Debian on RaspberryPi
- branch/revision: 2:12.0-0ubuntu1~bionic

**Comment by itkach** [comment]
Voting on a computer where baking is running is an obvious, but not the only use case. Another possibility - actually a recommended/preferred one - is to execute voting on a different machine using a backup/duplicate ledger device. For this only tezos-client needs to be installed.

**Comment by itkach** [comment]
even on a machine for baking is set up, requiring tezos-baking-mainnet is wrong. I had to start all the services manually because using tezos-baking-mainnet fails for me: it takes longer than 5s for node to start responding to endorser, but endorser service gives up after 5, shuts down which causes systemd to restart other service dependencies of tezos-baking-mainnet including tezos-node and it never gets out of this cycle.

**Comment by pasqu4le** [comment]
AFAIK the advantage of using baking services is that the voting wizard will be able to automatically figure out:
- the `client` data directory
- the node RPC address
- the baker alias to vote with

@ixahedron can correct me if I'm wrong tho

I agree that it shouldn't be a requirement. IMO the wizard should:
1. check if the baking service is running and look for those info automatically
2. if not found: ask the user some question to gather the necessary info (sensible defaults are good here)
3. if found: ask for confirmation (as it does already). If not confirmed, fall back to asking the user
