### ISSUE TITLE
[BUG] tezos-voting-wizard asks to choose mainnet vs custom network

### ISSUE THREAD

**Issue by itkach** [serokell/tezos-packaging#402]
# Description

Voting on custom network is only interesting to testers and developers. Regular users will only ever vote on mainnet. For regular users having to choose network first is an a confusing, unnecessary first step. Network is determined by Tezos node to which tezos-client connects. This can default to a local node and should fall back to a some public mainnet node and also be configurable as a command line option.

# To Reproduce

- run tezos-voting-wizard
- observe prompt to choose network

# Expected behavior

- tezos-voting-wizard immediately displays network's governance info and voting choice

**Comment by pasqu4le** [comment]
> be configurable as a command line option

I agree, the current first step should not exist and instead be moved to a command-line option (with mainnet as default if not specified).

**Comment by pasqu4le** [comment]
Currently the wizard still relies on the existence of a running baking service.
So, support for using only a node will be added in the scope of #401
