### ISSUE TITLE
How to speed up the synchronization of the main chain?

### ISSUE THREAD

**Issue by panchengj** [serokell/tezos-packaging#407]
How to speed up the synchronization of the main chain? Now it takes too long to synchronize once，it takes three seconds to synchronize a block now.

**Comment by pasqu4le** [comment]
If you are running your node for the first time, I suggest using [snapshots](http://tezos.gitlab.io/user/snapshots.html) with a [rolling history mode](http://tezos.gitlab.io/user/history_modes.html) to get your node bootstrapped as soon as possible (note that you may have to wait for some syncing anyway, depending on how old your snapshot is).

If you are using one of Ubuntu packages from this repository, the easiest way to set this up is to run the `tezos-setup-wizard`, see the [simplest procedure in the README]( https://github.com/serokell/tezos-packaging#set-up-a-node-andor-baking-on-ubuntu).

Aside from that 3 seconds per block I think is more or less what's expected currently from the node.
If you are trying to improve performance I suggest asking questions on the [Tezos StackExchange](https://tezos.stackexchange.com/) or getting more involved with the community on the [`tezos-dev`](https://tezos-dev.slack.com/) and [`tezos-baking`](https://tezos-baking.slack.com/) slack.

**Comment by itkach** [comment]
@panchengj in my experience hardware makes all the difference. For example, on a RaspberryPi4 with tezos data directory on an SSD drive, it is not uncommon to see block handled in 0.5 - 2.5 seconds; on a 6-year old Intel Xeon I see the same blocks routinely handled in under 300ms. If you observe typical complete times for a block > 3s - that's worse than a RaspberryPi  and you need to seriously reconsider your hardware or investigate performance of your virtualization setup if that's what you use.  Aside from CPU, storage performance is a factor  (SSD recommended) and so is networking (wired connection is recommended). Having said this, this is not directly related to this packaging project and I agree with  @pasqu4le that other venues he mentions are better places to ask this question.

**Comment by panchengj** [comment]
i'am  useing archive mode , could i use a  available snapshot ?

**Comment by itkach** [comment]
For baking, rolling mode is recommended. Archival and full nodes require significantly more storage and are not required for baking. There are no tezos snapshots for archival mode. Archival node can be created by syncing from scratch, by converting full node (import full snapshot and then run command to reconstruct tezos context), or via archival node data tarball, see https://medium.com/the-aleph/fast-node-sync-with-tezos-tarballs-4d74fb0da4f8 . But you don't need this for baking, I can't stress this enough.
