### ISSUE TITLE
Update to Ithaca

### ISSUE THREAD

**Issue by yashbhavsar007** [serokell/tezos-packaging#421]
# Clarification and motivation
Want to run two daemons together to support a smooth transition between Hangzhou and Ithaca. 

# Acceptance criteria
Can anyone produce any doc on how to run two daemons parallelly to have a smooth transition into the Ithaca without missing any baking and endorsement?

**Comment by rvem** [comment]
Hi!
In case you're using Ubuntu or Fedora, the easiest way to set up all required Octez binaries to run in the background would be to use `tezos-baking` systemd services. For more information, please refer to [this doc](https://github.com/serokell/tezos-packaging/blob/master/docs/baking.md).
As an alternative, you may use systemd services separately, see [this doc](https://github.com/serokell/tezos-packaging/blob/master/docs/systemd.md). (This doc also explains how you can use systemd services on non-Ubuntu/Fedora systems).
If you're using macOS, you can use background `launchd` services, see [another doc](https://github.com/serokell/tezos-packaging/blob/master/docs/distros/macos.md#launchd-background-services-on-macos).

**Comment by yashbhavsar007** [comment]
Thank you @rvem A feature for a smooth transition before 31st March will be really helpful for the bakers. Once again Thank you.

**Comment by rvem** [comment]
Can the issue be closed now?

**Comment by yashbhavsar007** [comment]
Yes, Thanks.

**Comment by yashbhavsar007** [comment]
@rvem Is there any set of instructions that we can manually do the transition for the new protocol upgrade? As it's already going to happen tomorrow I believe it's hard to introduce the new functionality in code that handles it automatically.

**Comment by rvem** [comment]
If you aren't using `systemd` services provided by the packages, you can still run all required binaries manually.
The list of binaries required for protocol transmission is the following:
1) `tezos-node`
2) `tezos-endorser-011-PtHangz2`
3) `tezos-baker-011-PtHangz2`
4) `tezos-baker-012-Psithaca`

Assuming that you already have a baking instance on mainnet, you should already have 1), 2), and 3) running. So the only thing you need to run additionally is `tezos-baker-012-Psithaca` and it should be run with the same arguments as `tezos-baker-011-PtHangz2`

**Comment by rvem** [comment]
If you're using `tezos-baking`, you shouldn't need to do anything additionally apart from updating all packages to `v12.0-3`.

If you aren't using `tezos-baking`, but use `systemd` other services and orchestrate them manually, you'll need to start `tezos-baker-012-psithaca.service` additionally.

**Comment by yashbhavsar007** [comment]
I use tezos-baking. I'll update to 12.0-3 today. I hope after updating the steps should be. 
1. `sudo systemctl start tezos-node-mainnet.service`
2. `sudo systemctl start tezos-baking-mainnet.service`

**Comment by rvem** [comment]
You shouldn't have to do any additional steps after packages upgrade. If you already have `tezos-baking-mainnet.service` running, it is supposed to be restarted automatically during the upgrade.

> After this I just need to sit back relax and wait for another update from you.

Yes, shortly after the protocol activation we'll push another update that will stop services Hangzhou daemons
