### ISSUE TITLE
[BUG] endorser binaries end with Hangzh2 

### ISSUE THREAD

**Issue by jnorthrup** [serokell/tezos-packaging#423]
the latest 12.03 release goes from hangzh2 to ithaca.  not ithaca2\

the endorser binary is not present for ithaca* 

should this release be avoided for april 1 switchover??

**Comment by rvem** [comment]
> the latest 12.03 release goes from hangzh2 to ithaca. not ithaca2\

Latest `tezos-baker-012-psithaca` package provides baker binary for `Psithaca2MLRFYargivpo7YvUr7wUDqyxrdhC5CQq78mRvimz6A`. You're probably confused by the lowercase in the protocol suffix, but it's prohibited to have uppercase characters in the packages' names. However, you may check that the binary that is actually installed is `tezos-baker-012-Psithaca`, not `tezos-baker-012-PsiThaCa` (the latter corresponds to ithaca).

> the endorser binary is not present for ithaca*

This is expected, see [v12.0 changelog](https://tezos.gitlab.io/releases/version-12.html#version-12-0).

**Comment by rvem** [comment]
> should this release be avoided for april 1 switchover??

The latest packages (`v12.0-3`) should provide a smooth transition from Hangzhou to Ithaca

**Comment by jnorthrup** [comment]
i went ahead and made the 16 gigabytes of build, because this is not documented anywhere that we now define <protocol> as "any meaningless string of letters following a dash" in tezos
