### ISSUE TITLE
Use xtz-shots snapshot metadata

### ISSUE THREAD

**Issue by pasqu4le** [serokell/tezos-packaging#441]
# Clarification and motivation

Our setup wizard has an option to import a snapshot, when setting up a new node, by downloading it from `xtz-shots.io`.

Currently this option is based on the fact that the latest snapshots there follow a predictable pattern and that we can "guess" the URL where we can find them.

Recently, however, they started serving snapshot metadata on `https://mainnet.xtz-shots.io/base.json`, which would be a much more stable mechanism, and asked for feedback on it.

We should attempt to use this in our wizard, to pick a snapshot to download, and help them fine-tune that endpoint it if possible.

**NOTE**: I think that this issue shouldn't be closed as soon as a PR for it is ready, specifically because we may go back and forth with them on the specifics of the endpoint mentioned above and its content.

# Acceptance criteria

The setup wizard picks what snapshot to download from `xtz-shots` using the metadata endpoint, rather than expecting it to match a URL format.

**Comment by ixahedron** [comment]
But we can still rely on the network part of the URL, do I understand correctly? As in, it'll always be `https://mainnet.xtz-shots.io/<...>` but maybe not `https://mainnet.xtz-shots.io/rolling`

**Comment by pasqu4le** [comment]
Upstream issues about where and how this metadata is served:
- [tezos-k8s/#446](https://github.com/oxheadalpha/tezos-k8s/issues/446)
- [tezos-k8s/#447](https://github.com/oxheadalpha/tezos-k8s/issues/447)

**Comment by ixahedron** [comment]
Upstream issue about JSON formatting: 
- [tezos-k8s/#451](https://github.com/oxheadalpha/tezos-k8s/issues/451)
