### ISSUE TITLE
Package transaction rollup Octez binaries

### ISSUE THREAD

**Issue by rvem** [serokell/tezos-packaging#453]
# Clarification and motivation
Jakarta protocol introduced new transaction rollup binaries, see the [list of artifacts](https://gitlab.com/tezos/tezos/-/jobs/2377360458/artifacts/browse/tezos-binaries/x86_64/) of `v13.0-rc1` Octez release candidate.

We should provide a convenient way to install these binaries on platforms that tezos-packaging project targets.

Note that some of these binaries may be supposed to be run as a background daemon and thus we should
provide systemd services for such binaries.

# Acceptance criteria

1) We provide static binaries, Ubuntu/Fedora packages, and brew formulae for new transaction rollup Octez binaries.
2) We provide systemd/launchd services for binaries that are supposed to be run as a background daemon.

**Comment by pasqu4le** [comment]
It seems that at the moment there isn't enough available docs, at least not to develop systemd services.

There are [rollup transactions docs](http://tezos.gitlab.io/alpha/transaction_rollups.html) but `rollup-node` and `rollup-client` are not described in the [shell CLI docs](http://tezos.gitlab.io/shell/cli-commands.html) nor the [jakarta CLI docs](http://tezos.gitlab.io/jakarta/cli-commands.html).

Related upstream issue: [tezos/#2601](https://gitlab.com/tezos/tezos/-/issues/2601)

**Comment by pasqu4le** [comment]
@krendelhoff it looks like there's an ongoing [documentation MR](https://gitlab.com/tezos/tezos/-/merge_requests/5058),but it's hard to say when it will be completed.

I think we should start releasing these binaries already, without any systemd/launchd services bundled in native packages yet and add them is a subsequent PR (unless by then the situation changes).

**Comment by pasqu4le** [comment]
I labeled this issue as `blocked` because as of now (upstream `v13.0` octez release) the rollup binaries should not be considered ready nor useful.

See [this PR thread](https://github.com/serokell/tezos-packaging/pull/479#discussion_r898104769) for more info.

So, putting this issue aside until there is an upstream release that includes complete rollup binaries

**Comment by pasqu4le** [comment]
Unblocking this issue because the [documentation MR](https://gitlab.com/tezos/tezos/-/merge_requests/5058) mentioned above has been completed and merged and these binaries should now be usable with Octez v14
