### ISSUE TITLE
Display useful snapshot metadata during node setup in wizard

### ISSUE THREAD

**Issue by rvem** [serokell/tezos-packaging#467]
# Clarification and motivation
Since #441 `tezos-setup-wizard` is going to use xtz-shots.io metadata for node snapshot files.
This metadata provides some information about snapshots e.g. snapshot head block hash, height, and timestamp.
Perhaps, it's worth showing some of this metadata in the setup wizard to give users some information about
how old the suggested snapshot is.

# Acceptance criteria

The setup wizard shows some information about the snapshot head block for snapshots from xtz-shots.io.

**Comment by krendelhoff2** [comment]
Resolved by #693 and #720
