### ISSUE TITLE
Depend on compatible version of opam in Ubuntu packages since 22.04

### ISSUE THREAD

**Issue by krendelhoff** [serokell/tezos-packaging#474]
# Clarification and motivation

`opam` [package](https://packages.ubuntu.com/jammy/opam) is `2.1.2` version Ubuntu 22.04 Jammy, but Octez is currently not compatible with `opam >= 2.1`.

# Acceptance criteria

All ubuntu packages depends on `opam < 2.1`.

**Comment by rvem** [comment]
I wasn't able to reproduce it using pbuilder on 22.04. Perhaps, `opam` received a fix. Let's close this issue and re-open once we have issues with `opam` again
