### ISSUE TITLE
Support 'ghostnet'

### ISSUE THREAD

**Issue by rvem** [serokell/tezos-packaging#487]
# Clarification and motivation
Ithacanet now targets to become a permanent testnet. Recently, the Jakarta protocol was activated on it.
Also, this testnet is now called `ghostnet`. We should support it in systemd services our packages provide.
A node config file for the `ghostnet` can be found here: https://teztnets.xyz/ghostnet.

# Acceptance criteria
`tezos-node` and `tezos-baking` packages provide services for running either node or a baking instance on `ghostnet`.

**Comment by rvem** [comment]
Apparently, it makes sense to remove `ithacanet` support as well

**Comment by nicolasochem** [comment]
octez v14 will support `--network ghostnet` natively so don't bother with the custom network config.

**Comment by rvem** [comment]
`ghostnet` support was added in `v14.0-rc1-1`, but the issue will be closed once the stable release with `ghostnet` support is published
