### ISSUE TITLE
Only support brew bottles for the last 2 macOS version

### ISSUE THREAD

**Issue by pasqu4le** [serokell/tezos-packaging#508]
# Clarification and motivation

We currently build and publish brew bottles for a number of macOS versions, some through buildkite (`big_sur` and `arm64_big_sur`) and others with GithHub Actions (`catalina`).

However the support for `catalina` is being phased out on GA, see https://github.com/actions/virtual-environments/issues/5583 due to the fact that:
> GitHub Actions maintains the latest two stable versions of any given OS version.

which is similar to what we do for other distribution methods.

We should follow this support policy, dropping bottle building for `catalina` and instead adding support for `monterey`, aiming at supporting the latest 2 stable version of macOS (at any given time).

# Acceptance criteria

- `catalina` bottle building is removed as phased out
- `monterey` bottle building is added, given that it's a stable macOS version
- `big_sur` bottle building is kept (best to use the existing machinery with `buildkite`, as it's faster and more reliable)
- the [support policy doc](https://github.com/serokell/tezos-packaging/blob/master/docs/support-policy.md) is updated accordingly, aiming at supporting the last 2 stable macOS versions available

**Comment by rvem** [comment]
> `mojave` bottle building is removed as well as the machinery needed to work with `buildkite`

Currently, we're building bottles for `big_sur` and `arm64_big_sur` on `buildkite` using a self-hosted runner.
And I think that our self-hosted runner is a bit more reliable than public GA runners (e.g. I had to retry a single job 5 times to get bottle built on `v14.0-rc1-1`)

**Comment by pasqu4le** [comment]
My bad, I was going off memory and made a mess, I changed the description and the acceptance criteria now
