### ISSUE TITLE
[BUG] No SSL or TLS support compiled into Conduit

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-packaging#52]
# Description

I am using `tezos-client` from the latest release and trying to connect to a node using TLS. I get an error: "No SSL or TLS support compiled into Conduit".

# To Reproduce

1. Use `tezos-client` from the 7.0-1 release.
2. Run any command that tries to connect to a functional remote node that uses TLS, for example:
> `tezos-client -S -A mainnet-tezos.giganode.io -P 443 rpc get /chains/main/blocks/head/protocols`
3. Get the following error:
```
Error:
  Rpc request failed:
     - meth: GET
     - uri: https://mainnet-tezos.giganode.io:443/describe/chains/main/blocks/head/protocols?recurse=no
     - error: Unable to connect to the node: "No SSL or TLS support compiled into Conduit"
```

# Expected behavior

I expect it to work the same way as `./carthagenet.sh client`
```
>  ./carthagenet.sh client -S -A mainnet-tezos.giganode.io -P 443 rpc get /chains/main/blocks/head/protocols
{ "protocol": "PsCARTHAGazKbHtnKfLzQg3kms52kSRpgnDY982a9oYsSXRLQEb",
  "next_protocol": "PsCARTHAGazKbHtnKfLzQg3kms52kSRpgnDY982a9oYsSXRLQEb" }
```

# Environment

- Archlinux
- v7.0-1 release

**Comment by gromakovsky** [comment]
`202003031020` revision works fine, so probably it was caused by switch to opam-nix.

**Comment by balsoft** [comment]
Yep, it's probably because I'm using conduit from OPAM and not from nixpkgs. I'll look into it.
