### ISSUE TITLE
new faucet

### ISSUE THREAD

**Issue by nicolasochem** [serokell/tezos-packaging#525]
The teztnets faucet has changed: instead of the traditional preaccount method, it now works based on simple transfers.

https://teztnets.xyz/

The setup wizard should be reworked to accomodate the new method:

```
nochem@peck ~/workspace/tezos-packaging () $ git grep faucet
docker/package/tezos_setup_wizard.py:    "if you plan on baking with a faucet JSON file.\n",
docker/package/tezos_setup_wizard.py:        "If you want to test baking with a faucet file, "
docker/package/wizard_structure.py:    prompt="Provide the path to your downloaded faucet JSON file.",
docker/package/wizard_structure.py:    help="Download the faucet JSON file from https://teztnets.xyz/.\n"
docs/baking.md:1) You have a faucet JSON file from https://teztnets.xyz/.
```

**Comment by pasqu4le** [comment]
AFAIK old JSON files, if anyone still have them, will keep working, so I suppose we can keep that option around for a while.

However we need to add a "generate new key" option when choosing how to import the baker key, to support the new faucet, as it's currently not supported.

Note: we still need to remove the URL from that JSON option and probably update some docs too :slightly_smiling_face:
