### ISSUE TITLE
'tezos' and 'opam-repository' flake inputs inhereted incorrectly when using 'tezos-packaging' as a flake input

### ISSUE THREAD

**Issue by rvem** [serokell/tezos-packaging#528]
# Clarification and motivation

When `tezos-packaging` flake is used as an input flake like
```
  inputs = {
    ...
    tezos-packaging = {
      url = "github:serokell/tezos-packaging?rev=663db49557927246c45a6e2c1126ffef5cb41e3d";
    };
    ...
  };
```

`tezos` and `opam-repository` inputs use the latest revision from the default branch instead of the revision pinned in 
`flake.lock` in this repo. As a result, an attempt to use packages from `tezos-packaging` flake may fail with a build error.

As an example, check https://github.com/serokell/aquarius-infra/blob/rvem/tezos-packaging-flake-issue/flake.nix and https://github.com/serokell/aquarius-infra/blob/rvem/tezos-packaging-flake-issue/flake.lock

# Acceptance criteria

`tezos` and `opam-repository` inputs are inherited correctly when using `tezos-packaging` flake as a input.

**Comment by krendelhoff2** [comment]
do i understand correctly that it is relevant specifically for non-flake inputs?

**Comment by rvem** [comment]
hmm, seems like flake inputs are affected as well (e.g. `opam-nix`), but it's not breaking as it with `tezos` and `opam-repository`

**Comment by balsoft** [comment]
@rvem which nix version did you use to create that lockfile? With `nix (Nix) 2.12.0pre20220901_4823067` I get "correct" results.

**Comment by rvem** [comment]
Don't seem to be the case with `nix 2.11.0` anymore
