### ISSUE TITLE
[BUG] `tezos-setup-wizard` works incorrectly on fedora

### ISSUE THREAD

**Issue by krendelhoff2** [serokell/tezos-packaging#546]
# Description

Seems like it's impossible to use `tezos-setup-wizard` without root permissions, which is incorrect behavior.

# Acceptance criteria
`tezos-setup-wizard` could run and sucessfully setup baking without root permissions

**Comment by pasqu4le** [comment]
> Also, no instantiated systemd services seem to be installed after setting up.

AFAIK those should be there after the installation, regardless of if one opens the wizard.

I think that this deserves it's own separate issue, do you mind splitting this one?

Also, please add an acceptance criteria to the description :slightly_smiling_face:
