### ISSUE TITLE
[BUG] tezos-setup does not honor custom node data directory when cleaning existing node data

### ISSUE THREAD

**Issue by itkach** [serokell/tezos-packaging#571]
tezos-setup wizard fails to initialize node in previously used  custom data

# To Reproduce
- set up tezos node with default data directory
- switch tezos node to use custom data directory (specify in /etc/default/tezos-node-mainnet)
- run tezos-setup-wizard, follow prompts and select to detele and bootstrap the node again
- observe wizard fails with "Invalid data directory" error

```
Would you like your setup to automatically start on boot?
1. yes (default)               Enable the services, running them both now and on every boot
2. no                          Start the services this time only
>
Trying to bootstrap octez-node
The Tezos node data directory already has some blockchain data:
identity.json
peers.json
store
lock
context

Delete this data and bootstrap the node again? <y/N> y

Node directory cleaned.
Which history mode do you want your node to run in?
1. rolling (default)           Store a minimal rolling window of chain data, lightest
                               option
2. full                        Store enough chain data to reconstruct the complete chain
                               state
3. archive                     Store all the chain data, very storage-demanding
>
Nov 23 14:48:23.117 - node.config.validation: the node configuration has been successfully validated.
The Tezos node can take a significant time to bootstrap from scratch.
Bootstrapping from a snapshot is suggested instead.
How would you like to proceed?
1. download rolling (default)  Import rolling snapshot from xtz-shots.io (recommended)
2. file                        Import snapshot from a file
3. url                         Import snapshot from a url
4. skip                        Skip snapshot import and synchronize with the network from
                               scratch
>
Downloading the snapshot from https://mainnet-v15.xtz-shots.io/mainnet-2909360.rolling
Progress: 100 %, 6123 MB
octez-node: Error:
              Invalid data directory '/mnt/extreme_ssd/tezos/node-mainnet': Please provide a clean directory by removing the following files: context.
```

# Expected behavior

tezos-setup clears data from from configured custom node data directory and successfully initialized new node  using that same directory

# Environment

- OS: RaspberryPi OS
- branch/revision: 2:15.0-0ubuntu1~bionic

**Comment by itkach** [comment]
> could it be due to permissions/ownership on the custom directory

I'm not sure why would that be the case: I had a perfectly running set up off of that custom directory and simply ran the wizard again to refresh my node (re-create it from snapshot) without changing any permissions. My impression is that the wizard cleared the default data directory (which also had existing node data from before I switched to custom directory) but by the time it started importing snapshot it "remember" that it should be using a different (custom) directory - hence the issue

> The wizard expects config.json and version.json to be present in the node data dir,

I don't see why or how this can possibly work. How config.json and version.json would appear in my custom data directory? Aren't default node data directories empty initially?

**Comment by itkach** [comment]
Sorry, didn't fully read your comment. I think package install time is not the right time to initialize directories, since it doesn't work for custom data directories. Wizard is probably also not the right place for it because services should be usable directly, without having to run wizard. Looks liken that leaves with daemon startup scripts as the only place for this.

**Comment by pasqu4le** [comment]
> package install time is not the right time to initialize directories, since it doesn't work for custom data directories.

I think it's not a bad idea to to initialize the default directories with the default parameters on installation.
There would be several issues however is if that's the only place where that happens.

> daemon startup scripts as the only place for this.

That's done already, on startup of a node service the config will be created (if missing, updated if there has been a change of options). You can try this yourself with an empty custom data dir, running `systemd start tezos-node-<network>` will work.

That's not sufficient for the wizard because a snapshot has to be imported _before_ the node service is launched (otherwise that will bootstrap from scratch) and _after_ the node data dir has been initialized (because without config the snapshot import won't work). 

So, it looks like this will have to fall on the wizard itself :confused:
