### ISSUE TITLE
[BUG] Octez version not available tag 16.0-1

### ISSUE THREAD

**Issue by vivienbcr** [serokell/tezos-packaging#628]
On ubuntu last release of serokell tezos package when i try to get octez node version it return :

```
octez-node --version                          
unknown (not-available) (0.0+dev)
```

Expected output is 16.0.

**Comment by vivienbcr** [comment]
Is this supposed to be released on ubuntu package  ?

**Comment by pasqu4le** [comment]
Yes, it has been released now, upgrading your installed packages should fix this issue.
