### ISSUE TITLE
Test packages installation for linux distros

### ISSUE THREAD

**Issue by pasqu4le** [serokell/tezos-packaging#641]
# Clarification and motivation

We publish native package for several versions of linux distro, but we don't always test all of them after publication.

For example, we recently had to upload the `tezos-sapling-params` package for some of our supported Fedora versions, the absence of which was causing most of our packages to not be installable.

We should prevent this by testing that the packages can be installed and their software executed (at least by running the `--version` option) on the regular.

It probably makes sense to automatically do this right after a new publication or perhaps on a schedule.

# Acceptance criteria

The latest packages published for linux distros at any given time are tested in all supported versions by CI, at least once, both for stable releases and RCs.

**Comment by PruStephan** [comment]
@pasqu4le can you give more clarifications on this issue? Specifically what packages do we want to test and on which Linux distros? For those tested is the `--version` running fine enough?

**Comment by pasqu4le** [comment]
> what packages do we want to test and on which Linux distros?

We need to test for Ubuntu and Fedora and for all the currently supported versions of both (see our [support policy](https://github.com/serokell/tezos-packaging/blob/master/docs/support-policy.md)).

We also need to check that all of our packages **from the current release** can be installed.

> For those tested is the --version running fine enough?

For packages containing binaries (e.g. the `tezos-client` package which contains the `octez-client` binary), yes, as mentioned in the description we can just check that calling their binaries with `--version` doesn't fail.

For `tezos-baking` I think that we should check that `tezos-setup` and `tezos-vote` can be called without failing too (although these are interactive wizards).

P.s. there is of course much more to test aside from this, but other issues will follow this one in the future.
