### ISSUE TITLE
Improve tezos revision updating process

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-packaging#66]
# Clarification and motivation

Our "Quick maintenance guide" says:
> Tezos revision is located in the [`sources.json`](../nix/nix/sources.json) file.
  You can either update it manually to newer revision or use `niv` tool.
  In order to do that run `niv update tezos` (this will update revision to latest).
  `niv update tezos -a rev=...` will update wources to some commit.

I'd like to pass just the tag and have `niv` to the trick. So I tried `niv update tezos -a rev=v7.3`. Here is what I got:
```
     "tezos": {
         "ref": "v7.2",
         "repo": "https://gitlab.com/tezos/tezos",
-        "rev": "6b9f3bc3c90d99d4a2bd5cd26e6f3efbcb977090",
+        "rev": "v7.3",
         "type": "git"
     }
 }
```

Apparently I should do `niv update tezos -a rev=ba45727cadd0416936fbd49400bcc986a55064ca -a ref=v7.3`.
Two problems:
1. Specifying `ba45727cadd0416936fbd49400bcc986a55064ca` is redundant (in theory).
2. Our guide doesn't say that both `-a` should be passed.

# Acceptance criteria

1. `s/wources/sources`.
2. This guide should say that the command should be run from `nix/`.
3. Research whether it's possible to specify only the tag and have `niv` figure out the revision. If it's not, open an issue in `niv`.
4. Update the `niv` command (in contribution guidelines) to have both `-a` arguments.

**Comment by gromakovsky** [comment]
One more thing: when we update Tezos revision we should update not only `sources.json`, but also `docker/build/Dockerfile`. That's not written in the maintenance guide.
1. At least we should write about it.
2. If we can somehow have version in only one place, that will be great.

**Comment by rvem** [comment]
> Research whether it's possible to specify only the tag and have niv figure out the revision. If it's not, open an issue in niv

Looks like there is already https://github.com/nmattia/niv/issues/141

**Comment by gromakovsky** [comment]
You forgot to upvote it :wink:
