### ISSUE TITLE
Improve the wizard prompts for ledger interactions

### ISSUE THREAD

**Issue by pasqu4le** [serokell/tezos-packaging#714]
# Clarification and motivation

The setup wizard can (depending on the choice) support a setup with a Ledger device.

It often isn't clear from the wizard itself, however, when an action is expected from the user, which leads to unnecessary waiting and/or confusion.

Note: IIRC in some cases `octez-client` itself prompts the user, but not every time

# Acceptance criteria

In every case in which the wizard is waiting for the user to do something with their Ledger device, this is shown in the wizard output.

**Comment by krendelhoff2** [comment]
Closed with #719
