### ISSUE TITLE
tezos-client cannot be installed on a container managed by Kubernetes

### ISSUE THREAD

**Issue by NeoDev42** [serokell/tezos-packaging#734]
# Clarification and motivation

We tried to install the `tezos-client` package in the following way from a container orchestrated by Kubernetes and it does not work:

```
$ sudo apt-get install -y tezos-client
Setting up tezos-client (2:18.0-0ubuntu3~focal) ...
Failed to send reload request: No such file or directory
dpkg: error processing package tezos-client (--configure):
 installed tezos-client package post-installation script subprocess returned error exit status 1
```
I tried to run the post-installation script directly by this way to check which line failed:

```
sh -x /var/lib/dpkg/info/tezos-client.postinst
```

And I got the same error, but in the script we have a very useful comment:

```
# Don't add udev rules in case the package is installed inside either docker or podman container.
# Otherwise, post-installation script will fail due to inability to non-zero exit code of the
# 'udevadm control --reload-rules' call
if [ ! -f /.dockerenv ] && [ ! -f /.containerenv ] ; then
    cat <<EOF > /etc/udev/rules.d/20-hw1.rules 
```

Nevertheless this test does not handle all cases, indeed in a container orchestrated by Kubernetes we have neither `.dockerenv` nor `.containerenv`.

By creating a fake `.dockerenv` , it works.

We must find a variable or the presence of an additional file to test if we are in a kubernetes pod.

# Acceptance criteria

Command `apt-get install -y tezos-client` MUST work from a Kubernetes pod.

**Comment by krendelhoff2** [comment]
@NeoDev42 we made a [new release](https://github.com/serokell/tezos-packaging/releases/tag/v18.0-4) containing fix, please run `apt-get update` and try to install one more time

**Comment by DMozhevitin** [comment]
Closing the issue for now
@NeoDev42 feel free to reopen it if this problem is relevant for the new release
