### ISSUE TITLE
[BUG] tezos-setup tries to register key as delegate even if it's already registered

### ISSUE THREAD

**Issue by DMozhevitin** [serokell/tezos-packaging#755]
# Description

When `baker` key is already registered as delegate, `tezos-setup` still shows the ledger prompt and calls `octez-client register key baker as delegate` command which fails with error. We need to skip these actions if the account has been already registered as delegate. It can be checked by querying `/context/delegates/<pkh>` node RPC endpoint.

# To Reproduce

1. Manually register the account used for baking in `tezos-setup` as delegate
2. Select this account in `tezos-setup`
3. Observe that `tezos-setup` shows the ledger prompt and calls `register key <key> as delegate` command which fails with error. The setup wizard won't fail with error though.

# Expected behavior

If the account is already a delegate, `tezos-setup` skip registering step.

# Environment

- Ubuntu 20.04
- `v18.1-1` release

**Comment by krendelhoff2** [comment]
fixed by #768
