### ISSUE TITLE
[BUG] PtParisB doesn't start  just like issue #777

### ISSUE THREAD

**Issue by scottwilkerson** [serokell/tezos-packaging#802]
# Description

systemctl restart tezos-baking-mainnet.service does not start/usr/bin/octez-baker-PtParisB

See issue #777 for same problem with last upgrade

**Comment by krendelhoff2** [comment]
@scottwilkerson Please do `apt update && apt upgrade`, make sure packages have `v20.0-3` version (they may still be uploading to the repository) and try again.

**Comment by scottwilkerson** [comment]
Works now, Thanks you!
