### ISSUE TITLE
Bump nixpkgs

### ISSUE THREAD

**Issue by rvem** [serokell/tezos-packaging#84]
# Clarification and motivation
Currently, this repo uses quite old nixpkgs which is incompatible with our other projects, when we try
to use ocaml overlay from this repo. Also it will impove caching.

I've tried to bump nixpkgs but wasn't able to do that quickly because a lot of things
was updated and new weird errors appeared.

# Acceptance criteria
This repo uses nixpkgs from our fork same as most of our other repos.

**Comment by gromakovsky** [comment]
> I've tried to bump nixpkgs but wasn't able to do that quickly because a lot of things was updated and new weird errors appeared.

You can make a PR so that new weird errors are visible to a broader audience.
