### ISSUE TITLE
Nix-less packaging

### ISSUE THREAD

**Issue by kirelagin** [serokell/tezos-packaging#9]
# Clarification and motivation

It might be useful for other parties who are not familiar with Nix to be able to set up their own packaging CD. Therefore we need an option of building the client binary without the help of Nix.

Since the packages will have to be built “natively”, preferable we should use distro-native C libraries. Using distro-native OCaml libraries would be great, if possible, but if not, looks like, we’ll have to bundle all transitive OCaml dependencies into our package. (It seems that OCaml links binaries dynamically only with C libraries, and all OCaml libraries are linked statically – if that is correct, then we are in luck.)

# Acceptance criteria

* The repo contains scripts/tools that can be used to build a `tezos-client` binary without Nix.
* There are scripts/tools that can be used to build Ubuntu and Fedora packages for `tezos-client`.
* There is documentation on how to use all of the above so that anyone can setup their own CD system using their favourite CD tool.

**Comment by gromakovsky** [comment]
#53 makes it possible to build static binaries without `nix`. However, our release creation scripts/files still use binaries built using `nix`. We should update them to use binaries built using `docker` way. 

I think it's fine to still use `nix` for this purpose if that's more convenient, but these files should be moved outside of `nix/` directory. I think `nix/` directory should be limited to files necessary to _build_ things with `nix`, and files that we use to create packages and release artifacts should be separated. Alternatively, we can still store all nix files in `nix/`, but have `nix/FOLDER_WITH_FILES_FOR_BUILDING` and `nix/FOLDER_WITH_FILES_FOR_RELEASING`.

**Comment by gromakovsky** [comment]
And please make a new release once that's done.
